import { test, expect } from './base.js';
import { mockEngine } from './mock.js';
import { readFile } from 'node:fs/promises';

// Generated by tools/MessageXmlFixture.java with the actual engine serializer.
// Synthetic only: exercises the Message/ConnectorMessage/MapContent converters.
const XML = await readFile(new URL('./fixtures/message-control-characters.xml', import.meta.url), 'utf8');
const RAW = '  SYNTHETIC-NCPDP\x1cFIELD\x1dGROUP\x1eSEGMENT\tLINE\nCR\r<>&"\' café 😀 \uE0000; &#x1c;  ';
const row = (id: number) => ({ messageId: id, channelId: 'c-started', processed: true,
    connectorMessages: { entry: { int: 0, connectorMessage: { metaDataId: 0, connectorName: 'Source', status: 'RECEIVED' } } } });
const fixtures = {
    'GET /channels/c-started/messages': { list: { message: [row(12345), row(12346)] } },
    'GET /channels/c-started/messages/12345': XML,
    'GET /channels/c-started/messages/12346': XML.replaceAll('12345', '12346').replace('SYNTHETIC-NCPDP', 'CURRENT-NCPDP'),
    'GET /channels/c-started/messages/*/attachments': { list: [] },
};

test('message XML preserves the real engine fixture and nested map contract', async ({ page }) => {
    await mockEngine(page, fixtures);
    await page.goto('/channels');
    await expect(page.locator('.shell')).toBeVisible();
    const result = await page.evaluate(async () => {
        const { default: api } = await import(String('/core/api.js'));
        const { mappingEntries } = await import(String('/core/xstream.js'));
        const message = await api.messages.get('c-started', 12345);
        const cm = message.connectorMessages.entry.connectorMessage;
        return { message, maps: mappingEntries(cm.sourceMapContent) };
    });
    const message = result.message;
    const cm = message.connectorMessages.entry.connectorMessage;
    expect(message.messageId).toBe(12345);
    expect(message.processed).toBe(true);
    expect(message.connectorMessages['@class']).toBe('linked-hash-map');
    expect(cm.raw.encrypted).toBe(false);
    expect(cm.raw.content).toBe(RAW);
    expect(cm.encoded.content).toBe('000123');
    expect(cm.transformed.content).toBe('false');
    expect(cm.processedRaw.content).toBe('null');
    expect(result.maps).toContainEqual(['controls', RAW]);
    expect(result.maps).toContainEqual(['numeric', '000123']);
    expect(result.maps).toContainEqual(['boolean', 'false']);
    expect(result.maps).toContainEqual(['typedBoolean', 'false']);
    expect(result.maps).toContainEqual(['typedInteger', '17']);
    expect(result.maps).toContainEqual(['nested', '{one=[0001, false]}']);
});

test('message detail negotiates XML, copies exact controls, and leaves no browser storage', async ({ page }) => {
    const requests: string[] = [];
    await mockEngine(page, { ...fixtures, 'GET /channels/c-started/messages/12345': (request: any) => {
        requests.push(request.headers().accept);
        return request.headers().accept === 'application/xml' ? XML : { __status: 500, body: 'JSON serialization failed' };
    } });
    await page.addInitScript(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: {
        writeText: async (value: string) => { (window as any).copiedMessage = value; }
    } }));
    await page.goto('/messages/c-started');
    await page.getByText('12345', { exact: true }).click();
    await page.getByRole('button', { name: 'Copy', exact: true }).click();
    expect(await page.evaluate(() => (window as any).copiedMessage)).toBe(RAW);
    expect(requests).toEqual(['application/xml']);
    for (const [tab, expected] of [['Encoded', '000123'], ['Transformed', 'false'], ['Processed Raw', 'null']]) {
        await page.getByRole('tab', { name: tab, exact: true }).click();
        await page.getByRole('button', { name: 'Copy', exact: true }).click();
        expect(await page.evaluate(() => (window as any).copiedMessage)).toBe(expected);
    }
    expect(await page.evaluate(() => JSON.stringify({ local: localStorage, session: sessionStorage }))).not.toContain('SYNTHETIC-NCPDP');
});

test('message parser preserves literal references, CDATA, attributes, binary strings and unknown metadata', async ({ page }) => {
    await mockEngine(page);
    await page.goto('/channels');
    const parsed = await page.evaluate(async () => {
        const { parseMessageXml } = await import(String('/core/message-xml.js'));
        const xml = '<message><messageId>9223372036854775807</messageId><connectorMessages class="linked-hash-map">'
            + '<entry><int>0</int><connectorMessage><metaDataId>0</metaDataId><raw><encrypted>false</encrypted><content>'
            + '&#x1C;&#29;&#x1e;&amp;#x1c;<![CDATA[&#x1d;\uE0000;<!DOCTYPE literal>]]>&#xE000;0;'
            + '</content></raw><encoded><content>AAEcHR7/+/==</content></encoded></connectorMessage></entry>'
            + '<entry><int>1</int><connectorMessage><metaDataId>1</metaDataId><sent reference="../../entry/connectorMessage/raw"/></connectorMessage></entry>'
            + '</connectorMessages><metadata><__proto__><polluted>true</polluted></__proto__><constructor>0005</constructor>'
            + '<parsererror>data</parsererror><value class="string" marker="&#x1c;"> false </value><unknown>0012</unknown>'
            + '<int>17</int><double>1.50</double><boolean>false</boolean><typed><list><int>17</int><boolean>false</boolean></list></typed>'
            + '<list><string>0001</string><string>false</string></list></metadata></message>';
        const message = parseMessageXml(xml);
        return { message, polluted: ({} as any).polluted, ownPrototype: Object.hasOwn(message.metadata, '__proto__') };
    });
    expect(parsed.message.messageId).toBe('9223372036854775807');
    expect(parsed.message.connectorMessages.entry[0].connectorMessage.raw.content).toBe('\x1c\x1d\x1e&#x1c;&#x1d;\uE0000;<!DOCTYPE literal>\uE0000;');
    expect(parsed.message.connectorMessages.entry[0].connectorMessage.encoded.content).toBe('AAEcHR7/+/==');
    expect(parsed.message.connectorMessages.entry[1].connectorMessage.sent['@reference']).toBe('../../entry/connectorMessage/raw');
    expect(parsed.message.metadata.value).toEqual({ '@class': 'string', '@marker': '\x1c', $: ' false ' });
    expect(parsed.message.metadata.unknown).toBe('0012');
    expect(parsed.message.metadata.constructor).toBe('0005');
    expect(parsed.message.metadata.int).toBe('17');
    expect(parsed.message.metadata.double).toBe('1.50');
    expect(parsed.message.metadata.boolean).toBe('false');
    expect(parsed.message.metadata.typed.list).toEqual({ int: 17, boolean: false });
    expect(parsed.message.metadata.list.string).toEqual(['0001', 'false']);
    expect(parsed.ownPrototype).toBe(true);
    expect(parsed.polluted).toBeUndefined();
});

test('nested Response and Sent envelopes decode controls without changing literal entities', async ({ page }) => {
    await mockEngine(page); await page.goto('/channels');
    const result = await page.evaluate(async () => {
        const { parseResponse } = await import(String('/core/xstream.js'));
        const { formatSentProperties } = await import(String('/core/sent-format.js'));
        return {
            response: parseResponse('<response><status>SENT</status><statusMessage>done</statusMessage><message>ACK&#x1c;&amp;#x1d;</message></response>'),
            sent: formatSentProperties('<com.mirth.connect.connectors.tcp.TcpDispatcherProperties><remoteAddress>localhost</remoteAddress><remotePort>1234</remotePort><template>DATA&#x1c;&amp;#x1d;</template></com.mirth.connect.connectors.tcp.TcpDispatcherProperties>')
        };
    });
    expect(result.response).toEqual({ status: 'SENT', statusMessage: 'done', message: 'ACK\x1c&#x1d;' });
    expect(result.sent).toContain('DATA\x1c&#x1d;');
});

for (const failure of ['malformed', 'wrong root', 'DTD', 'invalid reference', '500', '401']) {
    test(`message detail ${failure} rejects safely without a JSON retry`, async ({ page }) => {
        let calls = 0;
        const bad: Record<string, any> = { malformed: '<message><content>broken', 'wrong root': '<html>error</html>',
            DTD: '<!DOCTYPE message [<!ENTITY x "unsafe">]><message><content>&x;</content></message>',
            'invalid reference': '<message><content>&#xD800;</content></message>',
            '500': { __status: 500, body: { error: 'synthetic detail unavailable' } }, '401': { __status: 401 } };
        await mockEngine(page, { ...fixtures, 'GET /channels/c-started/messages/12345': () => { calls++; return bad[failure]; } });
        await page.goto('/messages/c-started');
        await page.getByText('12345', { exact: true }).click();
        if (failure === '401') await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible();
        else await expect(page.getByRole('dialog', { name: 'Error', exact: true })).toContainText(failure === '500' ? 'synthetic detail unavailable' : 'invalid message XML');
        expect(calls).toBe(1);
        await expect(page.locator('.content-toolbar')).toHaveCount(0);
    });
}

for (const late of ['success', 'failure']) {
    test(`message detail ignores a stale ${late} after selection changes`, async ({ page }) => {
        let release!: () => void;
        const gate = new Promise<void>(resolve => { release = resolve; });
        let started = false;
        await mockEngine(page, { ...fixtures, 'GET /channels/c-started/messages/12345': async () => {
            started = true; await gate; return late === 'success' ? XML : { __status: 500, body: 'stale failure' };
        } });
        await page.goto('/messages/c-started');
        await page.getByText('12345', { exact: true }).click();
        await expect.poll(() => started).toBe(true);
        await page.getByText('12346', { exact: true }).click();
        await expect(page.locator('.content-toolbar')).toBeVisible();
        const lateResponse = page.waitForResponse(response => new URL(response.url()).pathname.endsWith('/messages/12345'));
        release();
        await (await lateResponse).finished();
        await page.evaluate(() => new Promise(resolve => setTimeout(resolve, 0)));
        await expect(page.getByRole('dialog', { name: 'Error', exact: true })).toHaveCount(0);
        const body = page.locator('.content-toolbar').locator('..').locator('pre');
        await expect(body).toContainText('CURRENT-NCPDP');
        await expect(body).not.toContainText('SYNTHETIC-NCPDP');
    });
}

test('message detail can retry a rejected XML response without keeping stale content', async ({ page }) => {
    let calls = 0;
    await mockEngine(page, { ...fixtures, 'GET /channels/c-started/messages/12345': () => ++calls === 1 ? '<message>broken' : XML });
    await page.goto('/messages/c-started');
    await page.getByText('12345', { exact: true }).click();
    const error = page.getByRole('dialog', { name: 'Error', exact: true });
    await expect(error).toContainText('invalid message XML');
    await error.getByRole('button', { name: 'Close', exact: true }).last().click();
    await page.getByText('12345', { exact: true }).click();
    await expect(page.locator('.content-toolbar').locator('..').locator('pre')).toContainText('SYNTHETIC-NCPDP');
    expect(calls).toBe(2);
});

test('message detail does not reuse an old selection after selecting A then B then A', async ({ page }) => {
    let release!: () => void;
    const gate = new Promise<void>(resolve => { release = resolve; });
    let calls = 0;
    await mockEngine(page, { ...fixtures, 'GET /channels/c-started/messages/12345': async () => {
        if (++calls === 1) { await gate; return XML.replace('SYNTHETIC-NCPDP', 'STALE-NCPDP'); }
        return XML;
    } });
    await page.goto('/messages/c-started');
    await page.getByText('12345', { exact: true }).click();
    await expect.poll(() => calls).toBe(1);
    await page.getByText('12346', { exact: true }).click();
    await expect(page.locator('.content-toolbar')).toBeVisible();
    await page.getByText('12345', { exact: true }).click();
    const body = page.locator('.content-toolbar').locator('..').locator('pre');
    await expect(body).toContainText('SYNTHETIC-NCPDP');
    const lateResponse = page.waitForResponse(response => new URL(response.url()).pathname.endsWith('/messages/12345'));
    release();
    await (await lateResponse).finished();
    await page.evaluate(() => new Promise(resolve => setTimeout(resolve, 0)));
    await expect(body).toContainText('SYNTHETIC-NCPDP');
    await expect(body).not.toContainText('STALE-NCPDP');
});

test('late attachment failure cannot post an error over a new message selection', async ({ page }) => {
    let release!: () => void;
    const gate = new Promise<void>(resolve => { release = resolve; });
    let started = false;
    await mockEngine(page, { ...fixtures, 'GET /channels/c-started/messages/12345/attachments': async () => {
        started = true; await gate; return { __status: 500, body: 'stale attachment failure' };
    } });
    await page.goto('/messages/c-started');
    await page.getByText('12345', { exact: true }).click();
    await expect.poll(() => started).toBe(true);
    await page.getByText('12346', { exact: true }).click();
    await expect(page.locator('.content-toolbar')).toBeVisible();
    const lateResponse = page.waitForResponse(response => new URL(response.url()).pathname.endsWith('/messages/12345/attachments'));
    release();
    await (await lateResponse).finished();
    await page.evaluate(() => new Promise(resolve => setTimeout(resolve, 0)));
    await expect(page.getByRole('dialog', { name: 'Error', exact: true })).toHaveCount(0);
    await expect(page.locator('.content-toolbar').locator('..').locator('pre')).toContainText('CURRENT-NCPDP');
});
