/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/*
 * Database Reader (DatabaseReceiverProperties) / Database Writer (DatabaseDispatcherProperties).
 *
 * React port: def.render(host, ctx) -> def.component(ctx) => JSX. Field schemas,
 * defaults, the Database Drivers manager modal, and the driver-dropdown async
 * population are reused VERBATIM. The driver dropdown is a `custom` field that
 * returns the original imperative <select> DOM node (populated from
 * server.databaseDrivers, falling back to a text input on error) with the
 * manage-drivers wrench as its `append` — the same elements the panel built.
 */
import { React } from './react-platform.js';
import { h, modal, textInput, select, icon, toast, clear, confirmDialog } from '@oie/web-ui';
import { ConnectorForm, PollSection, asBool, YES_NO, defaultSourceProperties, defaultDestinationProperties, defaultPollProperties, CHARSETS, requireFields } from './react-forms.js';
import api from '../core/api.js';
const DRIVER_DEFAULT = 'Please Select One';
/* The JDBC drivers list is fetched once and cached for the lifetime of the
   editor (it's a server-global list); the wrench-save invalidates it so the
   dropdown picks up edits. Caching here means a form repaint (e.g. toggling a
   refresh field) reuses the list instead of re-fetching — matching the
   imperative panel, which fetched once at field creation + on wrench-save. */
let driversPromise = null;
function loadDrivers(platform) {
    if (!driversPromise)
        driversPromise = platform.api.server.databaseDrivers();
    return driversPromise;
}
/* Boilerplate "Connection" code generators (Swing generateConnectionString /
   generateUpdateConnectionString). Pure client-side string building from the
   driver/url/username/password fields — no server call — matching the engine
   character-for-character so the generated JavaScript is identical, EXCEPT that
   values are escaped for the single-quoted literals they land in: a password
   containing ' or \ otherwise produces a script that doesn't parse. */
const rhinoStr = (v) => String(v || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'");
function generateConnectionString(p) {
    return 'var dbConn;\n' +
        '\ntry {\n\tdbConn = DatabaseConnectionFactory.createDatabaseConnection(\'' +
        rhinoStr(p.driver) + '\',\'' + rhinoStr(p.url) + '\',\'' +
        rhinoStr(p.username) + '\',\'' + rhinoStr(p.password) +
        '\');\n\n\t// You may access this result below with $(\'column_name\')\n\treturn result;\n} finally {' +
        '\n\tif (dbConn) { \n\t\tdbConn.close();\n\t}\n}';
}
/* Reader post-process connection boilerplate (DatabaseReader.generateUpdateConnectionString).
   The leading comment varies with the post-process mode (each row vs once) and an
   extra note is added when results are aggregated. updateMode: UPDATE_EACH=3. */
function generateUpdateConnectionString(p) {
    let s = '';
    if (Number(p.updateMode) === 3) {
        s += '// This update script will be executed once for every result returned from the above query.\n';
    }
    else {
        s += '// This update script will be executed once after all results have been processed.\n';
    }
    if (asBool(p.aggregateResults)) {
        s += '// If "Aggregate Results" is enabled, you have access to "results",\n// a List of Map objects representing all rows returned from the above query.\n';
    }
    s += 'var dbConn;\n' +
        '\ntry {\n\tdbConn = DatabaseConnectionFactory.createDatabaseConnection(\'' +
        rhinoStr(p.driver) + '\',\'' + rhinoStr(p.url) + '\',\'' +
        rhinoStr(p.username) + '\',\'' + rhinoStr(p.password) +
        '\');\n\n} finally {' +
        '\n\tif (dbConn) { \n\t\tdbConn.close();\n\t}\n}';
    return s;
}
/* Writer connection boilerplate (DatabaseWriter.generateConnectionString) — like
   the reader's but with no leading comment and no "return result" line. */
function generateWriterConnectionString(p) {
    return 'var dbConn;\n' +
        '\ntry {\n\tdbConn = DatabaseConnectionFactory.createDatabaseConnection(\'' +
        rhinoStr(p.driver) + '\',\'' + rhinoStr(p.url) + '\',\'' +
        rhinoStr(p.username) + '\',\'' + rhinoStr(p.password) +
        '\');\n\n} finally {' +
        '\n\tif (dbConn) { \n\t\tdbConn.close();\n\t}\n}';
}
/* "Insert URL Template" button (Swing insertURLTemplateButton): fills the URL
   field with the selected driver's JDBC URL template, confirming first when a
   URL is already present (matching insertURLTemplateButtonActionPerformed). */
function insertUrlTemplateButton(properties, platform, onChange) {
    return h('button.btn', {
        type: 'button', class: 'ml-1.5',
        onClick: async () => {
            const drivers = await loadDrivers(platform).catch(() => []);
            const d = drivers.find((x) => x && String(x.className) === String(properties.driver));
            const template = d && d.template ? String(d.template) : '';
            if (!template) {
                toast('所选驱动没有 URL 模板。', 'warn');
                return;
            }
            if (properties.url && !(await confirmDialog('插入 URL 模板', '确定要用模板 URL 替换当前连接 URL 吗？', { okLabel: '替换' })))
                return;
            properties.url = template;
            onChange();
        }
    }, '插入 URL 模板');
}
/* The Driver <select> DOM node, populated asynchronously from the cached drivers
   list (falling back to a free-text input on error). Mirrors the imperative
   driverSelectField; the wrench append opens the drivers modal. */
function driverControlNode(properties, platform, onChange) {
    const wrap = h('div', { class: 'flex items-center gap-1.5' });
    const wrench = h('button.icon-btn', {
        type: 'button', title: '查看并管理数据库 JDBC 驱动列表',
        class: 'ml-1.5',
        onClick: () => openDriversModal(() => { driversPromise = null; refresh(); })
    }, icon('settings'));
    function rebuild(control) {
        clear(wrap);
        wrap.appendChild(control);
        wrap.appendChild(wrench);
    }
    function refresh() {
        loadDrivers(platform).then((drivers) => {
            const options = [{ value: DRIVER_DEFAULT, label: DRIVER_DEFAULT }];
            for (const d of drivers) {
                if (d && d.className)
                    options.push({ value: d.className, label: d.name || d.className });
            }
            const current = properties.driver;
            if (current && !options.some((o) => o.value === current)) {
                options.push({ value: current, label: current });
            }
            const sel = select(options, properties.driver ?? DRIVER_DEFAULT, {
                onChange: (e) => { properties.driver = e.target.value; onChange(); }
            });
            sel.style.width = '220px';
            rebuild(sel);
        }).catch(() => {
            // Engine unreachable: fall back to a free-text driver-class input.
            const input = textInput(properties.driver ?? '', {
                placeholder: 'org.postgresql.Driver',
                onChange: (e) => { properties.driver = e.target.value; onChange(); }
            });
            input.style.width = '220px';
            rebuild(input);
        });
    }
    // Initial render: a static select with the current driver while loading.
    const initial = select([{ value: properties.driver ?? DRIVER_DEFAULT, label: properties.driver ?? DRIVER_DEFAULT }], properties.driver ?? DRIVER_DEFAULT, { onChange: (e) => { properties.driver = e.target.value; onChange(); } });
    initial.style.width = '220px';
    rebuild(initial);
    refresh();
    return wrap;
}
/* Database Drivers manager — a modal table of DriverInfo records (Name, Driver
   Class, JDBC URL Template, Select with Limit Query, Legacy Driver Classes) with
   Add/Remove, persisted via PUT /server/databaseDrivers. Mirrors the Swing
   DatabaseDriversDialog. `onSaved` lets the connector refresh its dropdown. */
async function openDriversModal(onSaved) {
    let model;
    try {
        const drivers = await api.server.databaseDrivers();
        model = drivers.map((d) => ({
            name: d.name || '', className: d.className || '', template: d.template || '',
            selectLimit: d.selectLimit || '',
            alt: api.asList(d.alternativeClassNames, 'string').map(String).filter(Boolean).join(', ')
        }));
    }
    catch (e) {
        toast(`无法加载驱动：${e.message}`, 'error');
        return;
    }
    const tbody = h('tbody');
    function rowEl(d) {
        const cell = (key, ph, w) => {
            const inp = textInput(d[key], { placeholder: ph, style: { width: w, maxWidth: '100%' } });
            inp.addEventListener('input', () => { d[key] = inp.value; });
            return h('td', { class: 'py-0.5 px-1' }, inp);
        };
        return h('tr', cell('name', '名称', '120px'), cell('className', 'com.example.Driver', '200px'), cell('template', 'jdbc:db://host:port/name', '220px'), cell('selectLimit', 'SELECT * FROM ? LIMIT 1', '180px'), cell('alt', 'legacy.Driver, ...', '160px'), h('td', { class: 'py-0.5 px-1' }, h('button.icon-btn', { type: 'button', title: '移除', onClick: () => { model.splice(model.indexOf(d), 1); renderRows(); } }, icon('x'))));
    }
    function renderRows() {
        clear(tbody);
        if (!model.length)
            tbody.appendChild(h('tr', h('td', { colSpan: 6, class: 'text-text-faint p-3' }, '暂无驱动，请点击添加')));
        else
            model.forEach((d) => tbody.appendChild(rowEl(d)));
    }
    renderRows();
    const table = h('table.dt', h('thead', h('tr', h('th', '名称'), h('th', '驱动类'), h('th', 'JDBC URL 模板'), h('th', '带 Limit 的查询语句'), h('th', '旧版驱动类'), h('th', ''))), tbody);
    const addBtn = h('button.btn', { type: 'button', onClick: () => { model.push({ name: '', className: '', template: '', selectLimit: '', alt: '' }); renderRows(); } }, icon('plus'), '添加');
    modal({
        title: '数据库驱动',
        size: 'xwide',
        body: h('div', { class: 'flex flex-col gap-2.5' }, h('div', addBtn), h('div', { class: 'max-h-[55vh] overflow-auto' }, table)),
        buttons: [
            { label: '关闭' },
            {
                label: '保存', primary: true,
                onClick: async () => {
                    const payload = model
                        .filter((d) => d.name.trim() || d.className.trim())
                        .map((d) => {
                        const alt = d.alt.split(/[,\n]/).map((s) => s.trim()).filter(Boolean);
                        return {
                            name: d.name.trim(),
                            className: d.className.trim(),
                            template: d.template,
                            selectLimit: d.selectLimit,
                            // List<String>: { string: [...] } when present, empty element otherwise.
                            alternativeClassNames: alt.length ? { string: alt } : ''
                        };
                    });
                    try {
                        await api.server.setDatabaseDrivers(payload);
                        toast('数据库驱动已保存');
                        onSaved && onSaved();
                    }
                    catch (e) {
                        toast(`保存失败：${e.message}`, 'error');
                        return false;
                    }
                }
            }
        ]
    });
}
const databaseReader = {
    defaults(version) {
        return {
            '@class': 'com.mirth.connect.connectors.jdbc.DatabaseReceiverProperties',
            '@version': version,
            pluginProperties: null,
            pollConnectorProperties: defaultPollProperties(version),
            sourceConnectorProperties: defaultSourceProperties(version),
            driver: DRIVER_DEFAULT,
            url: '',
            username: '',
            password: '',
            select: '',
            update: '',
            useScript: false,
            aggregateResults: false,
            cacheResults: true,
            keepConnectionOpen: true,
            updateMode: 1,
            retryCount: '3',
            retryInterval: '10000',
            fetchSize: '1000',
            encoding: 'DEFAULT_ENCODING'
        };
    },
    component({ properties, platform, onChange }) {
        return (React.createElement("div", null,
            React.createElement(PollSection, { properties: properties, onChange: onChange }),
            React.createElement(ConnectorForm, { properties: properties, onChange: onChange, fields: [
                    { section: '连接设置' },
                    { type: 'custom', label: '驱动', render: () => driverControlNode(properties, platform, onChange) },
                    { key: 'url', label: 'URL', type: 'text', width: '420px', append: (p, ctx) => insertUrlTemplateButton(p, platform, ctx.onChange) },
                    { key: 'username', label: '用户名', type: 'text', width: '220px' },
                    { key: 'password', label: '密码', type: 'password', width: '220px' },
                    { section: '数据库读取器设置' },
                    {
                        // Swing useScriptYes/NoActionPerformed: toggling re-seeds the editors —
                        // Yes fills the Select + Post-Process editors with the connection
                        // boilerplate (and switches them to JavaScript); No clears them back to SQL.
                        key: 'useScript', label: '使用 JavaScript', type: 'radio', options: YES_NO, refresh: true,
                        onSet: (p, v) => {
                            if (asBool(v)) {
                                p.select = generateConnectionString(p);
                                p.update = generateUpdateConnectionString(p);
                            }
                            else {
                                p.select = '';
                                p.update = '';
                            }
                        }
                    },
                    // Swing useScriptYes/No: Keep Connection Open is disabled in JavaScript mode.
                    { key: 'keepConnectionOpen', label: '保持连接打开', type: 'radio', options: YES_NO, disabled: (p) => asBool(p.useScript) },
                    // Swing aggregateResultsActionPerformed(true): forces Cache Results=Yes and disables it.
                    {
                        key: 'aggregateResults', label: '聚合结果', type: 'radio', options: YES_NO, refresh: true,
                        onSet: (p) => { if (asBool(p.aggregateResults))
                            p.cacheResults = true; }
                    },
                    // Swing: Cache Results enabled only when Use JavaScript=No AND Aggregate Results=No.
                    { key: 'cacheResults', label: '缓存结果', type: 'radio', options: YES_NO, refresh: true, disabled: (p) => asBool(p.useScript) || asBool(p.aggregateResults) },
                    // Swing: Fetch Size enabled only when Use JavaScript=No AND Cache Results=No (aggregate forces cache=Yes).
                    { key: 'fetchSize', label: '获取行数', type: 'number', width: '110px', disabled: (p) => asBool(p.useScript) || asBool(p.cacheResults) || asBool(p.aggregateResults) },
                    { key: 'retryCount', label: '错误时重试次数', type: 'number', width: '110px' },
                    { key: 'retryInterval', label: '重试间隔（毫秒）', type: 'number', width: '120px' },
                    { key: 'encoding', label: '编码', type: 'select', options: CHARSETS, width: '160px' },
                    { section: '查询' },
                    {
                        // Swing flips selectSQLLabel 'SQL:'<->'JavaScript:' + the editor syntax on Use JavaScript.
                        key: 'select', label: (p) => asBool(p.useScript) ? 'JavaScript' : 'SQL', type: 'code', minHeight: '260px',
                        language: (p) => asBool(p.useScript) ? 'javascript' : 'sql',
                        tooltip: 'SQL 查询语句；当「使用 JavaScript」为「是」时填 JavaScript 脚本'
                    },
                    {
                        // Swing option labels (UPDATE_NEVER=1, UPDATE_EACH=3, UPDATE_ONCE=2);
                        // runPostProcessSQLLabel flips 'SQL'<->'Script' on Use JavaScript.
                        key: 'updateMode', label: (p) => asBool(p.useScript) ? '执行后处理脚本' : '执行后处理 SQL', type: 'radio', refresh: true,
                        // Swing aggregateResultsActionPerformed relabels the per-message
                        // options to per-row when Aggregate Results = Yes.
                        options: (p) => asBool(p.aggregateResults)
                            ? [{ value: 1, label: '从不' }, { value: 3, label: '每行一次' }, { value: 2, label: '全部行一次' }]
                            : [{ value: 1, label: '从不' }, { value: 3, label: '每条消息后' }, { value: 2, label: '全部消息后一次' }]
                    },
                    {
                        // Swing updateNeverActionPerformed keeps this editor VISIBLE but disabled at Never.
                        // The `code` field now honours `disabled`, so match Swing: grey it out (not hide it).
                        key: 'update', label: (p) => asBool(p.useScript) ? 'JavaScript' : 'SQL', type: 'code', minHeight: '260px',
                        language: (p) => asBool(p.useScript) ? 'javascript' : 'sql',
                        disabled: (p) => Number(p.updateMode) === 1
                    }
                ] })));
    },
    // Swing DatabaseReader.checkProperties: URL required unless Use JavaScript; the
    // SQL/JavaScript select is always required; the post-process SQL/script is
    // required unless Run Post-Process = Never (UPDATE_NEVER = 1); Driver required.
    validate(properties) {
        return requireFields(properties, [
            { key: 'url', label: 'URL', when: (p) => !asBool(p.useScript) },
            { key: 'select', label: 'SQL' },
            { key: 'update', label: '后处理 SQL', when: (p) => Number(p.updateMode) !== 1 },
            { key: 'driver', label: '驱动' }
        ]);
    }
};
const databaseWriter = {
    defaults(version) {
        return {
            '@class': 'com.mirth.connect.connectors.jdbc.DatabaseDispatcherProperties',
            '@version': version,
            pluginProperties: null,
            destinationConnectorProperties: defaultDestinationProperties(version),
            driver: DRIVER_DEFAULT,
            url: '',
            username: '',
            password: '',
            query: '',
            parameters: null,
            useScript: false
        };
    },
    component({ properties, platform, onChange }) {
        return (React.createElement(ConnectorForm, { properties: properties, onChange: onChange, fields: [
                { section: '连接设置' },
                { type: 'custom', label: '驱动', render: () => driverControlNode(properties, platform, onChange) },
                { key: 'url', label: 'URL', type: 'text', width: '420px', append: (p, ctx) => insertUrlTemplateButton(p, platform, ctx.onChange) },
                { key: 'username', label: '用户名', type: 'text', width: '220px' },
                { key: 'password', label: '密码', type: 'password', width: '220px' },
                { section: '查询' },
                {
                    // Swing useJavaScriptYes/NoActionPerformed: toggling re-seeds the editor —
                    // Yes fills it with the connection boilerplate (and switches to JavaScript);
                    // No clears it back to SQL.
                    key: 'useScript', label: '使用 JavaScript', type: 'radio', options: YES_NO, refresh: true,
                    onSet: (p, v) => { p.query = asBool(v) ? generateWriterConnectionString(p) : ''; }
                },
                {
                    // Swing flips sqlLabel 'SQL:'<->'JavaScript:' + the editor syntax on Use JavaScript.
                    key: 'query', label: (p) => asBool(p.useScript) ? 'JavaScript' : 'SQL', type: 'code', minHeight: '260px',
                    language: (p) => asBool(p.useScript) ? 'javascript' : 'sql'
                }
            ] }));
    },
    // Swing DatabaseWriter.checkProperties: URL required unless Use JavaScript; the
    // SQL/JavaScript query is always required; Driver required (must not be blank).
    validate(properties) {
        return requireFields(properties, [
            { key: 'url', label: 'URL', when: (p) => !asBool(p.useScript) },
            { key: 'query', label: 'SQL' },
            { key: 'driver', label: '驱动' }
        ]);
    }
};
export function register(platform) {
    platform.registerConnectorPanel('Database Reader', 'SOURCE', databaseReader);
    platform.registerConnectorPanel('Database Writer', 'DESTINATION', databaseWriter);
}
