/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/*
 * Connector framework — registers the generic JSON fallback ('*') used for any
 * connector type without a dedicated panel (e.g. a third-party connector with
 * no web UI yet).
 *
 * The bundled transports now load as plugins (plugins/connector-*); their panel
 * implementations live in this shared client connector library (./vm.jsx,
 * ./tcp.jsx, …) and build on the shared React form layer (./react-forms.jsx,
 * which re-exports the pure ./forms.js helpers) — the web equivalent of Mirth's
 * client-core that connector extensions depend on.
 *
 * React port: the generic fallback panel's render(host, ctx) becomes
 * component(ctx) => JSX (a raw-properties JSON editor + Apply). The 'Basic' TCP
 * transmission mode stays imperative (its settings dialog is a modal); the
 * frame helpers live in ./forms.js and ship to the mllpmode plugin too.
 */
import { React, useRef, useEffect } from './react-platform.js';
import { toast, createCodeEditor } from '@oie/web-ui';
import { frameModeSampleFrame, frameModeSettingsDialog } from './forms.js';
/* Raw-JSON fallback panel: a code editor over the connector properties with an
   Apply button. Mutates `properties` in place (preserving '@class'/'@version')
   and calls onChange — identical semantics to the imperative version. */
function GenericPanel({ properties, onChange }) {
    const hostRef = useRef(null);
    const editorRef = useRef(null);
    useEffect(() => {
        const host = hostRef.current;
        const editor = createCodeEditor({
            value: JSON.stringify(properties, null, 2),
            language: 'text',
            minHeight: '320px'
        });
        editorRef.current = editor;
        host.appendChild(editor.el);
        return () => { try {
            editor.dispose && editor.dispose();
        }
        catch { /* baseline no-op */ } editorRef.current = null; if (host)
            host.replaceChildren(); };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);
    const apply = () => {
        let parsed;
        try {
            parsed = JSON.parse(editorRef.current.getValue());
        }
        catch (e) {
            toast('JSON 无效：' + e.message, 'error');
            return;
        }
        if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
            toast('属性必须是一个 JSON 对象', 'error');
            return;
        }
        for (const key of Object.keys(properties)) {
            if (!(key in parsed))
                delete properties[key];
        }
        Object.assign(properties, parsed);
        onChange();
        toast('属性已应用');
    };
    return (React.createElement("div", null,
        React.createElement("div", { className: "hint mb-1.5" }, "\u6B64\u8FDE\u63A5\u5668\u7C7B\u578B\u6CA1\u6709\u4E13\u7528\u7F16\u8F91\u5668 \u2014\u2014 \u8BF7\u76F4\u63A5\u7F16\u8F91\u539F\u59CB\u5C5E\u6027 JSON\u3002\u5FC5\u987B\u4FDD\u7559 \"@class\" \u4E0E \"@version\"\u3002"),
        React.createElement("div", { ref: hostRef }),
        React.createElement("div", { className: "mt-2" },
            React.createElement("button", { className: "btn btn-primary", onClick: apply }, "\u5E94\u7528"))));
}
function genericPanel() {
    return {
        defaults(version) {
            return { '@version': version };
        },
        component: GenericPanel
    };
}
export function register(platform) {
    platform.registerConnectorPanel('*', 'SOURCE', genericPanel());
    platform.registerConnectorPanel('*', 'DESTINATION', genericPanel());
    // Basic TCP transmission mode (no framing) — the built-in TransmissionMode;
    // MLLP framing ships as the mllpmode plugin.
    platform.registerTransmissionMode('Basic', {
        label: '基本 TCP', order: 20,
        apply(tm) {
            tm['@class'] = 'com.mirth.connect.model.transmission.framemode.FrameModeProperties';
            tm.pluginPointName = 'Basic';
            tm.startOfMessageBytes = '';
            tm.endOfMessageBytes = '';
            // Drop MLLP-only fields when switching away from MLLP.
            delete tm.useMLLPv2;
            delete tm.ackBytes;
            delete tm.nackBytes;
            delete tm.maxRetries;
        },
        sampleFrame: frameModeSampleFrame,
        openSettings: frameModeSettingsDialog
    });
}
