/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/*
 * SMTP Sender (SmtpDispatcherProperties).
 *
 * React port: def.render(host, ctx) -> def.component(ctx) => JSX. Field schema +
 * defaults reused VERBATIM; the 'Send Test Email' button is the React
 * <ConnectorTestButton> (calls the same /connectors/smtp/_sendTestEmail servlet).
 *
 * Field order, labels and gating mirror the Swing SmtpSender panel
 * (engine client/.../connectors/smtp/SmtpSender.java initLayout/setProperties):
 *   SMTP Host (+ Send Test Email), SMTP Port, Override Local Binding,
 *   Local Address, Local Port, Send Timeout (ms), Encryption, Use Authentication,
 *   Username, Password, To, From, Subject, Charset Encoding, HTML Body, Body,
 *   Headers (Use Table/Use Map: table-or-map-variable), Attachments
 *   (Use Table/Use List: 3-column Name/Content/MIME-type table or list variable).
 */
import { React } from './react-platform.js';
import { h, clear, textInput, icon } from '@oie/web-ui';
import { ConnectorForm, connectorTestButton, asBool, YES_NO, defaultDestinationProperties, CHARSETS, requireFields } from './react-forms.js';
const usingAuth = (p) => asBool(p.authentication);
const usingLocalBinding = (p) => asBool(p.overrideLocalBinding);
/* SMTP attachments are a single java.util.ArrayList of
 * com.mirth.connect.connectors.smtp.Attachment objects (name/content/mimeType),
 * serialized by XStream under that FQN key. This mirrors the Swing
 * setAttachments/getAttachments 3-column (Name/Content/MIME type) table editor. */
const ATTACHMENT_CLASS = 'com.mirth.connect.connectors.smtp.Attachment';
function attachmentEntries(list) {
    if (!list || typeof list !== 'object')
        return [];
    const value = list[ATTACHMENT_CLASS];
    if (value === null || value === undefined || value === '')
        return [];
    return (Array.isArray(value) ? value : [value]).map((a) => ({
        name: String((a && a.name) ?? ''),
        content: String((a && a.content) ?? ''),
        mimeType: String((a && a.mimeType) ?? '')
    }));
}
function writeAttachments(list, rows) {
    const target = list && typeof list === 'object' ? list : {};
    if (!target['@class'])
        target['@class'] = 'java.util.ArrayList';
    const clean = rows.filter((r) => r.name !== '' || r.content !== '' || r.mimeType !== '');
    if (clean.length) {
        target[ATTACHMENT_CLASS] = clean.map((r) => ({ name: r.name, content: r.content, mimeType: r.mimeType }));
    }
    else {
        delete target[ATTACHMENT_CLASS];
    }
    return target;
}
/* Custom 3-column (Name / Content / MIME type) attachments table — the React
 * port of SmtpSender.setAttachments + New/Delete buttons. When `disabled` (the
 * "Use List:" variable mode), the rows and New button are greyed and the whole
 * block is dimmed — matching Swing useAttachmentsVariableFieldsEnabled() which
 * setEnabled(false) on the table + New/Delete but keeps it VISIBLE. */
function attachmentsTable(properties, onChange, disabled) {
    const wrap = h('div', disabled ? { class: 'opacity-60' } : {});
    const rows = attachmentEntries(properties.attachments);
    const commit = () => {
        properties.attachments = writeAttachments(properties.attachments, rows);
        onChange();
    };
    function paint() {
        clear(wrap);
        rows.forEach((row, i) => {
            wrap.appendChild(h('div', { class: 'flex gap-1.5 mb-1.5' }, textInput(row.name, { placeholder: '名称', disabled, class: 'flex-1', onInput: (e) => { row.name = e.target.value; commit(); } }), textInput(row.content, { placeholder: '内容', disabled, class: 'flex-[2]', onInput: (e) => { row.content = e.target.value; commit(); } }), textInput(row.mimeType, { placeholder: 'MIME 类型', disabled, class: 'flex-1', onInput: (e) => { row.mimeType = e.target.value; commit(); } }), h('button.icon-btn', { type: 'button', title: '移除', disabled, onClick: disabled ? null : () => { rows.splice(i, 1); commit(); paint(); } }, icon('x'))));
        });
        wrap.appendChild(h('button.btn', { type: 'button', disabled, onClick: disabled ? null : () => { rows.push({ name: '', content: '', mimeType: '' }); paint(); } }, '新建'));
    }
    paint();
    return wrap;
}
const smtpSender = {
    defaults(version) {
        return {
            '@class': 'com.mirth.connect.connectors.smtp.SmtpDispatcherProperties',
            '@version': version,
            pluginProperties: null,
            destinationConnectorProperties: defaultDestinationProperties(version),
            smtpHost: '',
            smtpPort: '25',
            overrideLocalBinding: false,
            localAddress: '0.0.0.0',
            localPort: '0',
            timeout: '5000',
            encryption: 'none',
            authentication: false,
            username: '',
            password: '',
            to: '',
            from: '',
            cc: '',
            bcc: '',
            replyTo: '',
            headers: { '@class': 'linked-hash-map' },
            headersVariable: '',
            isUseHeadersVariable: false,
            subject: '',
            charsetEncoding: 'DEFAULT_ENCODING',
            html: false,
            body: '',
            attachments: { '@class': 'java.util.ArrayList' },
            attachmentsVariable: '',
            isUseAttachmentsVariable: false
        };
    },
    component({ properties, channel, onChange }) {
        return (React.createElement("div", null,
            React.createElement(ConnectorForm, { properties: properties, onChange: onChange, fields: [
                    { section: '连接设置' },
                    { key: 'smtpHost', label: 'SMTP 主机', type: 'text', width: '200px', append: () => connectorTestButton({ label: '发送测试邮件', icon: 'mail', path: '/connectors/smtp/_sendTestEmail', channel, properties }) },
                    { key: 'smtpPort', label: 'SMTP 端口', type: 'number', width: '90px' },
                    { key: 'overrideLocalBinding', label: '覆盖本地绑定', type: 'radio', options: YES_NO, refresh: true },
                    { key: 'localAddress', label: '本地地址', type: 'text', width: '200px', disabled: (p) => !usingLocalBinding(p) },
                    { key: 'localPort', label: '本地端口', type: 'number', width: '90px', disabled: (p) => !usingLocalBinding(p) },
                    { key: 'timeout', label: '发送超时（毫秒）', type: 'number', width: '120px' },
                    { key: 'encryption', label: '加密', type: 'radio', options: [
                            { value: 'none', label: '无' },
                            { value: 'TLS', label: 'STARTTLS' },
                            { value: 'SSL', label: 'SSL' }
                        ] },
                    { key: 'authentication', label: '使用认证', type: 'radio', options: YES_NO, refresh: true },
                    { key: 'username', label: '用户名', type: 'text', width: '220px', disabled: (p) => !usingAuth(p) },
                    { key: 'password', label: '密码', type: 'password', width: '220px', disabled: (p) => !usingAuth(p) },
                    { section: '邮件设置' },
                    { key: 'to', label: '收件人', type: 'text', tooltip: '邮件要发送到的邮箱名称（通常是人）。' },
                    { key: 'from', label: '发件人', type: 'text', width: '220px' },
                    { key: 'subject', label: '主题', type: 'text' },
                    { key: 'charsetEncoding', label: '字符集编码', type: 'select', options: CHARSETS, width: '160px' },
                    { key: 'html', label: 'HTML 正文', type: 'radio', options: YES_NO },
                    { key: 'body', label: '正文', type: 'code', minHeight: '260px' },
                    { key: 'isUseHeadersVariable', label: '邮件头', type: 'radio', refresh: true, options: [
                            { value: false, label: '使用表格' },
                            { value: true, label: '使用映射：' }
                        ] },
                    // Swing useHeadersVariableFieldsEnabled() greys BOTH the table and the
                    // variable field (setEnabled) — both stay VISIBLE. Grey-both, not swap.
                    { key: 'headers', type: 'keyvalue', mapShape: 'string', disabled: (p) => asBool(p.isUseHeadersVariable) },
                    { key: 'headersVariable', label: '映射变量', type: 'text', width: '320px', disabled: (p) => !asBool(p.isUseHeadersVariable) },
                    { key: 'isUseAttachmentsVariable', label: '附件', type: 'radio', refresh: true, options: [
                            { value: false, label: '使用表格' },
                            { value: true, label: '使用列表：' }
                        ] },
                    // Swing useAttachmentsVariableFieldsEnabled() greys BOTH the table and the
                    // variable field (setEnabled) — both stay VISIBLE. Grey-both, not swap. The
                    // 'custom' branch doesn't propagate disabled, so derive it inside render().
                    { type: 'custom', label: '', span: true,
                        render: (p) => attachmentsTable(p, onChange, asBool(p.isUseAttachmentsVariable)) },
                    { key: 'attachmentsVariable', label: '列表变量', type: 'text', width: '320px', disabled: (p) => !asBool(p.isUseAttachmentsVariable) }
                ] })));
    },
    // Swing SmtpSender.checkProperties: SMTP Host, SMTP Port, Send Timeout, To and
    // From are always required. Local Address (Swing checks length() <= 3) and
    // Local Port are required when Override Local Binding is on. The headers/
    // attachments variable is required when the matching Use Map/Use List mode is on.
    validate(properties) {
        return requireFields(properties, [
            { key: 'smtpHost', label: 'SMTP 主机' },
            { key: 'smtpPort', label: 'SMTP 端口' },
            { key: 'localAddress', label: '本地地址', when: usingLocalBinding },
            { key: 'localPort', label: '本地端口', when: usingLocalBinding },
            { key: 'timeout', label: '发送超时' },
            { key: 'to', label: '收件人' },
            { key: 'from', label: '发件人' },
            { key: 'headersVariable', label: '邮件头映射变量', when: (p) => asBool(p.isUseHeadersVariable) },
            { key: 'attachmentsVariable', label: '附件列表变量', when: (p) => asBool(p.isUseAttachmentsVariable) }
        ]);
    }
};
export function register(platform) {
    platform.registerConnectorPanel('SMTP Sender', 'DESTINATION', smtpSender);
}
