/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/*
 * TCP Listener (TcpReceiverProperties) / TCP Sender (TcpDispatcherProperties).
 *
 * React port: def.render(host, ctx) -> def.component(ctx) => JSX. Field schemas
 * and defaults reused VERBATIM. The transmission-mode block (a plugin point:
 * Basic built-in + MLLP plugin) is the React <TransmissionModePanel>; the
 * connector test button keeps its imperative DOM node via the form's `append`.
 */
import { React } from './react-platform.js';
import { checkbox } from '@oie/web-ui';
import { ConnectorForm, TransmissionModePanel, connectorTestButton, portsInUseButton, listenerAddressField, asBool, YES_NO, defaultSourceProperties, defaultDestinationProperties, defaultListenerProperties, CHARSETS, requireFields } from './react-forms.js';
function defaultFrameMode() {
    return {
        '@class': 'com.mirth.connect.model.transmission.framemode.FrameModeProperties',
        pluginPointName: 'MLLP',
        startOfMessageBytes: '0B',
        endOfMessageBytes: '1C0D'
    };
}
const tcpListener = {
    defaults(version) {
        return {
            '@class': 'com.mirth.connect.connectors.tcp.TcpReceiverProperties',
            '@version': version,
            pluginProperties: null,
            listenerConnectorProperties: defaultListenerProperties(version, '6661'),
            sourceConnectorProperties: defaultSourceProperties(version, {
                responseVariable: 'Auto-generate (After source transformer)',
                firstResponse: true
            }),
            transmissionModeProperties: defaultFrameMode(),
            serverMode: true,
            remoteAddress: '',
            remotePort: '',
            overrideLocalBinding: false,
            reconnectInterval: '5000',
            receiveTimeout: '0',
            bufferSize: '65536',
            maxConnections: '10',
            keepConnectionOpen: true,
            dataTypeBinary: false,
            charsetEncoding: 'DEFAULT_ENCODING',
            respondOnNewConnection: 0,
            responseAddress: '',
            responsePort: '',
            responseConnectorPluginProperties: null
        };
    },
    component({ properties, onChange }) {
        // Server binds and listens locally; Client connects out to a remote
        // address. Swing's modeServer/modeClientRadioActionPerformed keep all the
        // mode-specific fields visible but toggle their enabled state.
        // asBool, not a strict compare: the engine wire shape can deliver
        // "true"/"false" strings, which a strict !== false read as Server mode
        // while validate() below read them as Client — an unresolvable save.
        const serverMode = (p) => asBool(p.serverMode);
        return (React.createElement("div", { className: "flex flex-col gap-4" },
            React.createElement(ConnectorForm, { properties: properties, onChange: onChange, fields: [
                    { section: '监听器设置' },
                    listenerAddressField('listenerConnectorProperties.host', '本地地址'),
                    { key: 'listenerConnectorProperties.port', label: '本地端口', type: 'number', width: '90px', append: () => portsInUseButton() }
                ] }),
            React.createElement(TransmissionModePanel, { properties: properties, onChange: onChange }),
            React.createElement(ConnectorForm, { properties: properties, onChange: onChange, fields: [
                    { section: 'TCP 监听器设置' },
                    { key: 'serverMode', label: '模式', type: 'radio', refresh: true, options: [
                            { value: true, label: '服务器' },
                            { value: false, label: '客户端' }
                        ] },
                    { key: 'remoteAddress', label: '远程地址', type: 'text', width: '200px', disabled: serverMode },
                    { key: 'remotePort', label: '远程端口', type: 'number', width: '90px', disabled: serverMode },
                    { key: 'overrideLocalBinding', label: '覆盖本地绑定', type: 'radio', options: YES_NO, disabled: serverMode },
                    { key: 'reconnectInterval', label: '重连间隔（毫秒）', type: 'number', width: '90px', disabled: serverMode },
                    { key: 'maxConnections', label: '最大连接数', type: 'number', width: '90px', disabled: (p) => !asBool(p.serverMode) },
                    { key: 'receiveTimeout', label: '接收超时（毫秒）', type: 'number', width: '90px', tooltip: '0 表示永不超时' },
                    { key: 'bufferSize', label: '缓冲区大小（字节）', type: 'number', width: '90px' },
                    { key: 'keepConnectionOpen', label: '保持连接打开', type: 'radio', options: YES_NO },
                    {
                        key: 'dataTypeBinary', label: '数据类型', type: 'radio', refresh: true,
                        // Binary disables Encoding and forces it back to the default (Swing setSelectedIndex(0)).
                        onSet: (p) => { if (asBool(p.dataTypeBinary))
                            p.charsetEncoding = 'DEFAULT_ENCODING'; },
                        options: [
                            { value: true, label: '二进制' },
                            { value: false, label: '文本' }
                        ]
                    },
                    { key: 'charsetEncoding', label: '编码', type: 'select', options: CHARSETS, width: '160px', disabled: (p) => asBool(p.dataTypeBinary) },
                    {
                        key: 'respondOnNewConnection', label: '新连接时响应', type: 'radio', refresh: true,
                        options: [
                            { value: 1, label: '是' },
                            { value: 0, label: '否' },
                            { value: 2, label: '消息恢复' }
                        ]
                    },
                    { key: 'responseAddress', label: '响应地址', type: 'text', width: '200px', disabled: (p) => Number(p.respondOnNewConnection) === 0 },
                    { key: 'responsePort', label: '响应端口', type: 'number', width: '90px', disabled: (p) => Number(p.respondOnNewConnection) === 0 }
                ] })));
    },
    // Shared ListenerSettingsPanel.checkProperties: Local Address + Local Port always
    // required. TcpListener.checkProperties: Remote Address/Port + Reconnect Interval
    // required in Client mode (!serverMode); Receive Timeout, Buffer Size and Max
    // Connections always required; Response Address/Port required unless Respond on
    // New Connection is No (0). Numeric/range checks (e.g. maxConnections > 0) skipped.
    validate(properties) {
        return requireFields(properties, [
            { key: 'listenerConnectorProperties.host', label: '本地地址' },
            { key: 'listenerConnectorProperties.port', label: '本地端口' },
            { key: 'remoteAddress', label: '远程地址', when: (p) => !asBool(p.serverMode) },
            { key: 'remotePort', label: '远程端口', when: (p) => !asBool(p.serverMode) },
            { key: 'reconnectInterval', label: '重连间隔（毫秒）', when: (p) => !asBool(p.serverMode) },
            { key: 'receiveTimeout', label: '接收超时（毫秒）' },
            { key: 'bufferSize', label: '缓冲区大小（字节）' },
            { key: 'maxConnections', label: '最大连接数' },
            { key: 'responseAddress', label: '响应地址', when: (p) => Number(p.respondOnNewConnection) !== 0 },
            { key: 'responsePort', label: '响应端口', when: (p) => Number(p.respondOnNewConnection) !== 0 }
        ]);
    }
};
const tcpSender = {
    defaults(version) {
        return {
            '@class': 'com.mirth.connect.connectors.tcp.TcpDispatcherProperties',
            '@version': version,
            pluginProperties: null,
            destinationConnectorProperties: defaultDestinationProperties(version, { validateResponse: true }),
            transmissionModeProperties: defaultFrameMode(),
            serverMode: false,
            remoteAddress: '127.0.0.1',
            remotePort: '6660',
            overrideLocalBinding: false,
            localAddress: '0.0.0.0',
            localPort: '0',
            sendTimeout: '5000',
            bufferSize: '65536',
            maxConnections: '10',
            keepConnectionOpen: false,
            checkRemoteHost: false,
            responseTimeout: '5000',
            ignoreResponse: false,
            queueOnResponseTimeout: true,
            dataTypeBinary: false,
            charsetEncoding: 'DEFAULT_ENCODING',
            template: '${message.encodedData}'
        };
    },
    component({ properties, channel, onChange }) {
        // Server binds and listens locally; Client connects out to a remote host.
        // Swing's modeServer/modeClientRadioActionPerformed keep every field
        // visible but toggle enabled state, then re-apply the override-binding and
        // keep-connection-open sub-gating in Client mode.
        const serverMode = (p) => asBool(p.serverMode);
        const localBindingDisabled = (p) => !asBool(p.serverMode) && !asBool(p.overrideLocalBinding);
        const sendDisabled = (p) => asBool(p.serverMode) || !asBool(p.keepConnectionOpen);
        return (React.createElement("div", null,
            React.createElement(TransmissionModePanel, { properties: properties, onChange: onChange }),
            React.createElement(ConnectorForm, { properties: properties, onChange: onChange, fields: [
                    { section: '连接设置' },
                    // Swing initLayout adds modeClientRadio then modeServerRadio
                    // (TcpSender.java:654-655), so on-screen order is Client, Server.
                    { key: 'serverMode', label: '模式', type: 'radio', refresh: true, options: [
                            { value: false, label: '客户端' },
                            { value: true, label: '服务器' }
                        ] },
                    {
                        key: 'remoteAddress', label: '远程地址', type: 'text', width: '200px', disabled: serverMode,
                        // Test Connection greys in Server mode (TcpSender.modeServerRadioActionPerformed).
                        append: (p) => connectorTestButton({ path: '/connectors/tcp/_testConnection', channel, properties, disabled: serverMode(p) })
                    },
                    { key: 'remotePort', label: '远程端口', type: 'number', width: '90px', disabled: serverMode },
                    { key: 'overrideLocalBinding', label: '覆盖本地绑定', type: 'radio', options: YES_NO, refresh: true, disabled: serverMode },
                    { key: 'localAddress', label: '本地地址', type: 'text', width: '200px', disabled: localBindingDisabled },
                    // Ports in Use follows the Local Port field: on in Server mode or Client+Override.
                    { key: 'localPort', label: '本地端口', type: 'number', width: '90px', append: (p) => portsInUseButton({ disabled: localBindingDisabled(p) }), disabled: localBindingDisabled },
                    { key: 'maxConnections', label: '最大连接数', type: 'number', width: '90px', disabled: (p) => !asBool(p.serverMode) },
                    { key: 'keepConnectionOpen', label: '保持连接打开', type: 'radio', options: YES_NO, refresh: true, disabled: serverMode },
                    { key: 'checkRemoteHost', label: '检查远程主机', type: 'radio', options: YES_NO, disabled: sendDisabled },
                    { key: 'sendTimeout', label: '发送超时（毫秒）', type: 'number', width: '90px', disabled: sendDisabled },
                    { key: 'bufferSize', label: '缓冲区大小（字节）', type: 'number', width: '90px' },
                    {
                        key: 'responseTimeout', label: '响应超时（毫秒）', type: 'number', width: '90px',
                        // Swing pairs the Ignore Response checkbox inline with Response Timeout;
                        // it gates Queue on Response Timeout below.
                        append: (p, ctx) => checkbox('忽略响应', asBool(p.ignoreResponse), {
                            onChange: (e) => { p.ignoreResponse = e.target.checked; ctx.onChange(); }
                        }).el
                    },
                    { key: 'queueOnResponseTimeout', label: '响应超时时入队', type: 'radio', options: YES_NO, disabled: (p) => asBool(p.ignoreResponse) },
                    {
                        key: 'dataTypeBinary', label: '数据类型', type: 'radio', refresh: true,
                        // Binary disables Encoding and forces it back to the default (Swing setSelectedIndex(0)).
                        onSet: (p) => { if (asBool(p.dataTypeBinary))
                            p.charsetEncoding = 'DEFAULT_ENCODING'; },
                        options: [
                            { value: true, label: '二进制' },
                            { value: false, label: '文本' }
                        ]
                    },
                    { key: 'charsetEncoding', label: '编码', type: 'select', options: CHARSETS, width: '160px', disabled: (p) => asBool(p.dataTypeBinary) },
                    { section: '模板' },
                    { key: 'template', label: '模板', type: 'code', minHeight: '260px' }
                ] })));
    },
    // Swing TcpSender.checkProperties: Remote Address/Port required in Client mode
    // (!serverMode); Local Address/Port required in Server mode or when Override Local
    // Binding is on; Max Connections required in Server mode; Send Timeout required in
    // Client mode with Keep Connection Open; Buffer Size, Response Timeout and Template
    // always required. Numeric/range checks (e.g. maxConnections > 0) skipped.
    validate(properties) {
        return requireFields(properties, [
            { key: 'remoteAddress', label: '远程地址', when: (p) => !asBool(p.serverMode) },
            { key: 'remotePort', label: '远程端口', when: (p) => !asBool(p.serverMode) },
            { key: 'localAddress', label: '本地地址', when: (p) => asBool(p.serverMode) || asBool(p.overrideLocalBinding) },
            { key: 'localPort', label: '本地端口', when: (p) => asBool(p.serverMode) || asBool(p.overrideLocalBinding) },
            { key: 'maxConnections', label: '最大连接数', when: (p) => asBool(p.serverMode) },
            { key: 'sendTimeout', label: '发送超时（毫秒）', when: (p) => !asBool(p.serverMode) && asBool(p.keepConnectionOpen) },
            { key: 'bufferSize', label: '缓冲区大小（字节）' },
            { key: 'responseTimeout', label: '响应超时（毫秒）' },
            { key: 'template', label: '模板' }
        ]);
    }
};
export function register(platform) {
    platform.registerConnectorPanel('TCP Listener', 'SOURCE', tcpListener);
    platform.registerConnectorPanel('TCP Sender', 'DESTINATION', tcpSender);
}
