/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/*
 * Channel Reader (VmReceiverProperties) / Channel Writer (VmDispatcherProperties).
 *
 * React port: the def.render(host, ctx) panels become def.component(ctx) => JSX.
 * Field schemas + defaults are reused VERBATIM; only the rendering layer is JSX.
 * The Channel Id dropdown keeps its original imperative <select> (populated
 * asynchronously from channels.idsAndNames) as a `custom` field — the same DOM
 * node the panel always built, mounted into the React form.
 */
import { React } from './react-platform.js';
import { h, clear, select, textInput, icon } from '@oie/web-ui';
import { ConnectorForm, mapEntries, defaultSourceProperties, defaultDestinationProperties } from './react-forms.js';
/* XStream List<String>: { '@class': 'java.util.ArrayList', string: [...] } */
function asArray(value) {
    if (value === null || value === undefined || value === '')
        return [];
    return Array.isArray(value) ? value : [value];
}
function stringList(list) {
    if (!list || typeof list !== 'object')
        return [];
    return asArray(list.string).map((v) => String(v ?? ''));
}
function writeStringList(list, values) {
    const target = list && typeof list === 'object' ? list : {};
    if (!target['@class'])
        target['@class'] = 'java.util.ArrayList';
    if (values.length)
        target.string = values;
    else
        delete target.string;
    return target;
}
const channelReader = {
    defaults(version) {
        return {
            '@class': 'com.mirth.connect.connectors.vm.VmReceiverProperties',
            '@version': version,
            pluginProperties: null,
            sourceConnectorProperties: defaultSourceProperties(version)
        };
    },
    component() {
        return (React.createElement("div", { className: "cform-section" },
            React.createElement("div", { className: "cform-section-title" }, "\u901A\u9053\u8BFB\u53D6\u5668\u8BBE\u7F6E"),
            React.createElement("div", { className: "hint py-0.5 px-0" }, "\u901A\u9053\u8BFB\u53D6\u5668\u76D1\u542C\u672C\u670D\u52A1\u5668\u4E0A\u5176\u4ED6\u901A\u9053\u8DEF\u7531\u8FC7\u6765\u7684\u6D88\u606F\uFF0C\u6CA1\u6709\u8FDE\u63A5\u5668\u4E13\u5C5E\u8BBE\u7F6E\u3002")));
    },
    // Swing ChannelReader.checkProperties() has no required-field checks (returns true).
    validate() { return []; }
};
/* Synthetic combo labels Swing surfaces when the text field holds a value that
   isn't a known channel id. They are never standing picker options and never
   written to channelId — they describe the field's current state, shown as the
   combo's selected value only while that state holds (see syncCombo). */
const NONE_LABEL = '<无>';
const MAP_VARIABLE_LABEL = '<映射变量>';
const NOT_FOUND_LABEL = '<通道未找到>';
/* Channel Id dual control, mirroring ChannelWriter's editable channelIdField
   (the source of truth) paired with the channelNames combo (a convenience
   picker). Both are rendered side-by-side and kept in two-way sync:
     - The free-text field is bound to properties.channelId so a user can type a
       RAW channel id or a Velocity map variable like ${channelId}. Swing stores
       'none' when the field is blank, so a blank field clears channelId to 'none'.
     - The combo is keyed by channel NAME and resolves to an id; '<None>' clears
       the field. Selecting an entry writes its id into the field (updateField in
       reverse). The combo's options are only <None> + channel names; a synthetic
       label (<Map Variable> / <Channel Not Found>) appears as the selected value
       only when the field holds a map variable or an unknown id — never as an option.
   Combo option order matches Swing: '<None>' first, then channels sorted
   alpha-numerically by NAME (Collections.sort on channelNameArray). */
function channelControlNode(properties, platform, onChange) {
    const wrap = h('div', { class: 'flex items-center gap-1.5' });
    // channelList: name -> id, used to resolve the combo selection and reverse-sync.
    let channelList = [];
    const field = textInput(properties.channelId === 'none' ? '' : (properties.channelId ?? ''), {
        placeholder: '<无>', title: '目标通道的唯一全局 ID。',
        class: 'w-[225px]'
    });
    const combo = select([{ value: NONE_LABEL, label: NONE_LABEL }], NONE_LABEL, {
        title: '选择要把本目的地过滤器接收到的消息写入哪个通道，选择“无”表示完全不写入消息。',
        class: 'w-[225px]'
    });
    // Reverse-sync the combo selection to whatever the field text holds, matching
    // ChannelWriter.updateField(): blank -> <None>, a known channel name (we store
    // id->name, so look up the name) -> that name, contains '$' -> <Map Variable>,
    // else -> <Channel Not Found>.
    function syncCombo() {
        const text = String(field.value ?? '');
        let selection;
        if (text.trim() === '') {
            selection = NONE_LABEL;
        }
        else {
            const match = channelList.find(([, id]) => id === text);
            if (match)
                selection = match[0];
            else if (text.includes('$'))
                selection = MAP_VARIABLE_LABEL;
            else
                selection = NOT_FOUND_LABEL;
        }
        // <Map Variable>/<Channel Not Found> describe the field's current value; they
        // are never standing picker options (matching Swing, whose combo model holds
        // only <None> + channel names while setSelectedItem can still *display* one of
        // these labels). Carry it as a hidden option only while it's the selection, so
        // the closed control shows it but the open dropdown lists only <None> + names.
        for (const opt of Array.from(combo.options)) {
            if (opt.value === MAP_VARIABLE_LABEL || opt.value === NOT_FOUND_LABEL)
                opt.remove();
        }
        if (selection === MAP_VARIABLE_LABEL || selection === NOT_FOUND_LABEL) {
            const opt = h('option', { value: selection }, selection);
            opt.hidden = true;
            combo.appendChild(opt);
        }
        combo.value = selection;
    }
    // The field is the source of truth: Swing stores 'none' for a blank field.
    field.addEventListener('input', () => {
        const text = field.value;
        properties.channelId = text.trim() === '' ? 'none' : text;
        syncCombo();
        onChange();
    });
    // Combo fills the field (channelNamesActionPerformed): '<None>' clears it; a
    // channel name resolves to its id. Synthetic labels are non-selectable no-ops.
    combo.addEventListener('change', () => {
        const name = combo.value;
        let id = null;
        if (name === NONE_LABEL)
            id = '';
        else {
            const match = channelList.find(([n]) => n === name);
            if (match)
                id = match[1];
        }
        if (id !== null) {
            field.value = id;
            properties.channelId = id.trim() === '' ? 'none' : id;
            onChange();
        }
        syncCombo();
    });
    wrap.appendChild(field);
    wrap.appendChild(combo);
    const status = h('span', { role: 'status', class: 'text-text-dim' });
    const refresh = h('button.btn', { type: 'button', onClick: () => { void load(); } }, '刷新通道');
    wrap.appendChild(refresh);
    wrap.appendChild(status);
    // The catalog belongs to this mounted control. Reopening or refreshing it
    // reads current names, and a rejected request never poisons later attempts.
    async function load() {
        refresh.disabled = true;
        combo.disabled = true;
        status.textContent = '正在加载通道…';
        try {
            const map = await platform.api.channels.idsAndNames();
            // mapEntries yields [channelId, channelName]; sort the picker by name.
            channelList = mapEntries(map)
                .map(([id, name]) => [name, id])
                .sort((a, b) => a[0].localeCompare(b[0]));
            clear(combo);
            // Synthetic labels describe the stored value, never selectable options.
            combo.appendChild(h('option', { value: NONE_LABEL }, NONE_LABEL));
            for (const [name] of channelList)
                combo.appendChild(h('option', { value: name }, name));
            syncCombo();
            status.textContent = '';
            combo.disabled = false;
        }
        catch {
            status.textContent = '无法加载通道。请刷新后重试，已保存的通道 ID 不受影响。';
        }
        finally {
            refresh.disabled = false;
        }
    }
    syncCombo();
    void load();
    return wrap;
}
/* Single-column "Map Variable" List<String> table (mapVariables), mirroring
   ChannelWriter.mapVariablesTable. The keys are injected into the source map of
   the destination channel's message; per the Swing tooltip, only the bare key is
   entered (no "${}" syntax). Each row carries its own inline Delete next to the
   variable; a New button below appends a row. */
function mapVariablesTable(properties, onChange) {
    const wrap = h('div');
    const rows = stringList(properties.mapVariables);
    const commit = () => {
        properties.mapVariables = writeStringList(properties.mapVariables, rows.filter((v) => v !== ''));
        onChange();
    };
    function uniqueName() {
        for (let i = 1; i <= rows.length + 1; i++) {
            const name = 'Variable ' + i;
            if (!rows.some((v) => v.toLowerCase() === name.toLowerCase()))
                return name;
        }
        return 'Variable ' + (rows.length + 1);
    }
    function paint() {
        clear(wrap);
        const table = h('div', { class: 'flex flex-col gap-1' });
        table.appendChild(h('div', { className: 'cform-label', class: 'font-semibold text-[11px]' }, '映射变量'));
        rows.forEach((value, i) => {
            const input = textInput(value, {
                placeholder: '映射变量', class: 'flex-1',
                onInput: (e) => { rows[i] = e.target.value; commit(); }
            });
            const delBtn = h('button.icon-btn', {
                type: 'button', title: '删除',
                onClick: () => { rows.splice(i, 1); commit(); paint(); }
            }, icon('x'));
            table.appendChild(h('div', { class: 'flex gap-1.5 mb-1 items-center' }, input, delBtn));
        });
        const newBtn = h('button.btn', {
            type: 'button',
            onClick: () => { rows.push(uniqueName()); commit(); paint(); }
        }, '新建');
        wrap.appendChild(table);
        wrap.appendChild(h('div', { class: 'mt-1.5' }, newBtn));
    }
    paint();
    return wrap;
}
const channelWriter = {
    defaults(version) {
        return {
            '@class': 'com.mirth.connect.connectors.vm.VmDispatcherProperties',
            '@version': version,
            pluginProperties: null,
            destinationConnectorProperties: defaultDestinationProperties(version),
            channelId: 'none',
            channelTemplate: '${message.encodedData}',
            mapVariables: { '@class': 'java.util.ArrayList' }
        };
    },
    component({ properties, platform, onChange }) {
        return (React.createElement(ConnectorForm, { properties: properties, onChange: onChange, fields: [
                { section: '通道写入器设置' },
                {
                    type: 'custom', label: '通道 ID', span: true,
                    tooltip: '目标通道的唯一全局 ID。可输入原始通道 ID 或 ${mapVariable}，也可从下拉框中选择通道以自动填入。',
                    render: () => channelControlNode(properties, platform, onChange)
                },
                {
                    type: 'custom', label: '消息元数据', span: true,
                    tooltip: '以下映射变量将写入目标通道消息的源映射中。请只填写映射键名本身，不要带 "${}" 语法。',
                    render: () => mapVariablesTable(properties, onChange)
                },
                { key: 'channelTemplate', label: '模板', type: 'code', minHeight: '340px' }
            ] }));
    },
    // Swing ChannelWriter.checkProperties() has no required-field checks (returns true).
    validate() { return []; }
};
export function register(platform) {
    platform.registerConnectorPanel('Channel Reader', 'SOURCE', channelReader);
    platform.registerConnectorPanel('Channel Writer', 'DESTINATION', channelWriter);
}
