/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/*
 * Engine REST API client.
 *
 * Requests use the deployment's engine API root: the Node server's /api reverse
 * proxy for standalone/Docker installs, or the co-located engine API for a WAR.
 * We ask the engine for JSON (Accept: application/json); its XStream serializer
 * wraps every payload in a single root key (e.g. {"list": ...},
 * {"channel": ...}) which is unwrapped here. Some endpoints still answer in
 * XML or plain text, so parsing falls back gracefully.
 *
 * Writes must round-trip the same wrapped shape, so put()/post() accept a
 * wrapKey. When editing complex objects (channels, settings) always fetch,
 * mutate, and send the same object back — that preserves "@class"/"@version"
 * attributes and any properties contributed by server-side plugins.
 */
import * as oie from './oie.js';
import { API_BASE } from './deployment.js';
import { engineFetch, assertEngineResponse } from './engine-fetch.js';
const BASE = API_BASE;
const listeners = { sessionExpired: [], engineUnknown: [] };
let sessionExpiredFired = false;
// Deep clone JSON-serializable data (channels are plain engine JSON), so write
// transforms don't mutate the object the editor still holds.
const cloneJson = (o) => JSON.parse(JSON.stringify(o));
// Staxon reads @-prefixed keys as XML attributes, which must precede child
// elements/text. The engine's reorder fallback skips arrays, so normalize at
// every JSON write boundary (including multipart parts). A replacer visits
// nested array items too, without changing editor objects or content order.
function stringifyEngineJson(value) {
    const ordered = new WeakMap();
    return JSON.stringify(value, (_key, node) => {
        if (!node || typeof node !== 'object' || Array.isArray(node))
            return node;
        if (ordered.has(node))
            return ordered.get(node);
        const entries = Object.entries(node);
        const attributes = entries.filter(([key]) => key.startsWith('@'));
        if (!attributes.length)
            return node;
        const result = Object.fromEntries([...attributes, ...entries.filter(([key]) => !key.startsWith('@'))]);
        // Reuse the replacement for shared references, retaining JSON.stringify's
        // normal circular-reference error rather than endlessly cloning a cycle.
        ordered.set(node, result);
        return result;
    });
}
// Returns an unsubscribe. Callers that register from a React effect MUST call it
// on cleanup: without one, a remount (StrictMode's double-invoke, or any future
// remount of the registering component) leaves a second handler behind and one
// 401 then fires the whole expiry flow twice — two stacked "session expired"
// modals over the login screen.
export function onSessionExpired(fn) {
    listeners.sessionExpired.push(fn);
    return () => {
        const i = listeners.sessionExpired.indexOf(fn);
        if (i >= 0)
            listeners.sessionExpired.splice(i, 1);
    };
}
// The server refused to route for this tab's engine selection (421
// ENGINE_UNKNOWN — the engine was removed or renamed, see server/proxy.js).
// Fires once, sharing the 401 latch: both mean "this session is over, head to
// the login screen". Same unsubscribe contract as onSessionExpired above.
export function onEngineUnknown(fn) {
    listeners.engineUnknown.push(fn);
    return () => {
        const i = listeners.engineUnknown.indexOf(fn);
        if (i >= 0)
            listeners.engineUnknown.splice(i, 1);
    };
}
/* Call after a successful re-login so the next 401 (or 421) fires again. */
export function resetSessionExpired() { sessionExpiredFired = false; }
/* ---- engine reachability ----------------------------------------------------
 * Observed from the traffic the app already makes — deliberately NOT a heartbeat.
 * A poll would keep resetting the ENGINE's own session inactivity timeout, which
 * is the same reason core/idle-logout.js runs its check loop without any network
 * call. So this only ever reports on requests some view actually asked for.
 *
 * "Reachable" means the engine answered, whatever it said: a 500 is an engine
 * with an opinion, and a 401 is an expired session (onSessionExpired's job, and a
 * different message to the user). Only a rejected fetch — DNS, refused connection,
 * dropped socket — or a gateway status, where the proxy is telling us the upstream
 * never answered, counts as unreachable.
 */
const GATEWAY_STATUSES = new Set([502, 503, 504]);
const connectionListeners = [];
let engineReachable = true;
/** Subscribe to reachability changes. Returns an unsubscribe (see onSessionExpired). */
export function onConnectionChange(fn) {
    connectionListeners.push(fn);
    return () => {
        const i = connectionListeners.indexOf(fn);
        if (i >= 0)
            connectionListeners.splice(i, 1);
    };
}
/** True while engine requests are getting answers. */
export function isEngineReachable() { return engineReachable; }
function setReachable(next) {
    if (next === engineReachable)
        return;
    engineReachable = next;
    for (const fn of connectionListeners.slice()) {
        try {
            fn(next);
        }
        catch { /* a bad listener must not break the request */ }
    }
}
/*
 * The single send path for every verb below. Wrapping fetch (rather than handle)
 * is what makes a network failure observable at all: a rejected fetch never
 * reaches handle().
 */
function send(url, init, opts) {
    // A hard ceiling so a wedged proxy/engine socket cannot hang a caller's
    // await forever (spinners that never resolve). Generous because legitimate
    // engine calls can be slow (large channel groups, message exports), and
    // overridable (RequestOptions.timeoutMs) because some operations are
    // legitimately open-ended: aborting them wouldn't stop the engine, only
    // orphan the work in flight.
    const timeoutMs = opts?.timeoutMs === undefined ? 120_000 : opts.timeoutMs;
    if (!init.signal && timeoutMs !== null)
        init.signal = AbortSignal.timeout(timeoutMs);
    return engineFetch(url, init).then((response) => {
        setReachable(!GATEWAY_STATUSES.has(response.status));
        return handle(response, opts);
    }, (err) => {
        // The ceiling above fired: the CLIENT stopped waiting. The bare
        // DOMException ("signal timed out") reads like an engine failure and
        // invites retrying an operation the engine may still be executing —
        // say what actually happened. A slow answer is also not an
        // unreachable engine, so reachability is left alone.
        if (err && err.name === 'TimeoutError') {
            throw new Error(`No response after ${Math.round(timeoutMs / 1000)} seconds — the web administrator stopped waiting. The engine may still be completing the operation; check its result before retrying.`);
        }
        setReachable(false);
        throw err;
    });
}
function headers(contentType) {
    const h = {
        // Prefer JSON, but accept anything — several endpoints (/server/version,
        // /server/id, /server/jvm, ...) produce only text/plain and answer 406
        // to a bare application/json Accept header.
        'Accept': 'application/json, text/plain;q=0.9, */*;q=0.8',
        'X-Requested-With': 'OpenIntegrationEngine-WebAdmin'
    };
    if (contentType)
        h['Content-Type'] = contentType;
    return h;
}
/** Thrown on a non-OK engine response. */
export class ApiError extends Error {
    status;
    /** The raw response text, when the failing response carried one. */
    body;
    constructor(status, message, body) {
        super(message);
        this.status = status;
        this.body = body;
    }
}
function unwrap(parsed) {
    // XStream JSON puts the payload under a single root key.
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        const keys = Object.keys(parsed);
        if (keys.length === 1)
            return parsed[keys[0]];
    }
    return parsed;
}
function xmlToObj(node) {
    if (!node.children || node.children.length === 0) {
        const text = node.textContent || '';
        if (text === 'true')
            return true;
        if (text === 'false')
            return false;
        if (/^-?\d+$/.test(text) && text.length < 16)
            return parseInt(text, 10);
        return text;
    }
    const obj = {};
    for (const child of node.children) {
        const value = xmlToObj(child);
        if (Object.prototype.hasOwnProperty.call(obj, child.tagName)) {
            if (!Array.isArray(obj[child.tagName]))
                obj[child.tagName] = [obj[child.tagName]];
            obj[child.tagName].push(value);
        }
        else {
            obj[child.tagName] = value;
        }
    }
    return obj;
}
/** Parse an engine response body (JSON or XML), unwrapping the XStream root key. */
export function parseBody(text) {
    if (!text)
        return null;
    const trimmed = text.trim();
    if (trimmed[0] === '{' || trimmed[0] === '[') {
        try {
            return unwrap(JSON.parse(trimmed));
        }
        catch { /* fall through */ }
    }
    if (trimmed[0] === '<') {
        try {
            const doc = new DOMParser().parseFromString(trimmed, 'text/xml');
            if (!doc.querySelector('parsererror'))
                return xmlToObj(doc.documentElement);
        }
        catch { /* fall through */ }
    }
    return trimmed;
}
async function handle(response, { raw = false, noAuthHandler = false } = {}) {
    if (response.status === 401) {
        // Auth endpoints (login / current) handle 401 themselves: a 401 there
        // means bad credentials or "not signed in", NOT an expired session, so
        // don't fire the global session-expired handler.
        if (noAuthHandler) {
            const text = await response.text().catch(() => '');
            assertEngineResponse(response);
            // parseBody is total (its parses are internally guarded), so no try/catch.
            let message = '未授权';
            const parsed = parseBody(text);
            if (parsed && typeof parsed === 'object')
                message = parsed.message || parsed.error || message;
            throw new ApiError(401, message, text);
        }
        // Background polls all hit 401 at once when the engine restarts —
        // notify only once so the login screen isn't re-rendered mid-typing.
        if (!sessionExpiredFired) {
            sessionExpiredFired = true;
            listeners.sessionExpired.forEach(fn => fn());
        }
        throw new ApiError(401, '会话已过期');
    }
    const text = await response.text();
    assertEngineResponse(response);
    if (!response.ok) {
        let message = text || `${response.status} ${response.statusText}`;
        // parseBody is total (its parses are internally guarded), so no try/catch.
        const parsed = parseBody(text);
        if (parsed && typeof parsed === 'object') {
            message = parsed.message || parsed.detailedError || parsed.error || message;
        }
        // 421: the web admin server refuses to route for this tab's remembered
        // engine selection (removed/renamed — server/proxy.js ENGINE_UNKNOWN).
        // The session cannot continue on any engine, so treat it like expiry —
        // fire once (same burst problem as 401 polls) and let the shell drop to
        // the login screen, where the picker demands an explicit re-pick
        // (issue #53). Same latch as 401: once we're headed to login, neither
        // handler needs to fire again.
        if (response.status === 421 && !noAuthHandler && !sessionExpiredFired) {
            sessionExpiredFired = true;
            listeners.engineUnknown.forEach(fn => fn());
        }
        throw new ApiError(response.status, message, text);
    }
    if (raw)
        return text;
    return parseBody(text);
}
// The engine's ChannelServlet parses startEdit with "yyyy-MM-dd'T'HH:mm:ssZ" — an
// RFC-822 offset with NO milliseconds (millis make SimpleDateFormat.parse throw,
// which silently falls back to "now" and breaks the concurrent-edit check). That's
// NOT standard ISO-8601, so Date.toISOString() (millis + 'Z') can't be sent as-is.
// Reshape the built-in ISO string to the engine's form — sent as UTC (+0000), since
// only the absolute instant matters (the engine compares Calendars): drop the
// ".SSS" and turn the trailing 'Z' into '+0000'.
function fmtStartEdit(d) {
    return d.toISOString().replace(/\.\d{3}Z$/, '+0000');
}
function qs(params) {
    if (!params)
        return '';
    const parts = [];
    for (const [key, value] of Object.entries(params)) {
        if (value === undefined || value === null || value === '')
            continue;
        for (const v of Array.isArray(value) ? value : [value]) {
            if (v === undefined || v === null)
                continue;
            parts.push(`${encodeURIComponent(key)}=${encodeURIComponent(v)}`);
        }
    }
    return parts.length ? '?' + parts.join('&') : '';
}
// Encode interpolated path segments (ids are server-generated UUIDs/numbers, so
// this is a no-op in practice — defense-in-depth against a stray reserved char).
const enc = encodeURIComponent;
export function get(path, params, opts) {
    return send(BASE + path + qs(params), {
        method: 'GET', headers: headers(), credentials: 'same-origin'
    }, opts);
}
export function post(path, body, { params, contentType = 'application/json', wrapKey, raw, noAuthHandler, timeoutMs } = {}) {
    let payload = body;
    if (body !== undefined && body !== null && typeof body !== 'string' && !(body instanceof FormData)) {
        payload = stringifyEngineJson(wrapKey ? { [wrapKey]: body } : body);
    }
    return send(BASE + path + qs(params), {
        method: 'POST',
        headers: body instanceof FormData ? headers() : headers(contentType),
        credentials: 'same-origin',
        body: payload ?? null
    }, { raw, noAuthHandler, timeoutMs });
}
export function put(path, body, { params, contentType = 'application/json', wrapKey, raw, timeoutMs } = {}) {
    let payload = body;
    if (body !== undefined && body !== null && typeof body !== 'string') {
        payload = stringifyEngineJson(wrapKey ? { [wrapKey]: body } : body);
    }
    return send(BASE + path + qs(params), {
        method: 'PUT', headers: headers(contentType), credentials: 'same-origin', body: payload ?? null
    }, { raw, timeoutMs });
}
/* ---- Raw XML content negotiation -------------------------------------------
   The engine's XStream serializer answers Accept: application/xml with the
   same XML the Swing Administrator reads/writes, and its JAX-RS endpoints
   consume raw application/xml bodies. These helpers skip all client-side
   (de)serialization so import/export round-trips are byte-faithful. */
export function getXml(path, params, opts) {
    return send(BASE + path + qs(params), {
        method: 'GET',
        headers: {
            'Accept': 'application/xml',
            'X-Requested-With': 'OpenIntegrationEngine-WebAdmin'
        },
        credentials: 'same-origin'
    }, { ...opts, raw: true });
}
export function postXml(path, xml, params) {
    return post(path, String(xml), { params, contentType: 'application/xml' });
}
export function putXml(path, xml, params) {
    return put(path, String(xml), { params, contentType: 'application/xml' });
}
export function del(path, params, opts) {
    return send(BASE + path + qs(params), {
        method: 'DELETE', headers: headers(), credentials: 'same-origin'
    }, opts);
}
/* When the engine returns a singleton or missing list, normalize to an array.
   XStream JSON renders one-element collections as a bare object, and classes
   without an @XStreamAlias use their fully-qualified name as the wrapper key
   (e.g. {"list":{"com.mirth...ServerLogItem":[...]}}). */
export function asList(value, key) {
    if (value === null || value === undefined || value === '')
        return [];
    if (key !== undefined && value && typeof value === 'object' && !Array.isArray(value)) {
        if (value[key] !== undefined) {
            value = value[key];
        }
        else {
            const keys = Object.keys(value).filter(k => !k.startsWith('@'));
            if (keys.length === 1) {
                const lastSegment = (keys[0].split('.').pop() ?? '').toLowerCase();
                // Unwrap when the lone key is the FQCN form of the expected
                // alias, or when it plainly holds the array we asked for.
                if (lastSegment === key.toLowerCase() || Array.isArray(value[keys[0]])) {
                    value = value[keys[0]];
                }
            }
        }
        if (value === null || value === undefined || value === '')
            return [];
    }
    return Array.isArray(value) ? value : [value];
}
/* ===========================================================================
   Authentication & users                                          /users
   ========================================================================== */
export const auth = {
    // Idle-timeout logout (Swing parity): a distinct engine operation so the event
    // log records "Logged out due to inactivity" instead of a plain logout.
    inactivityLogout: () => post('/users/_inactivityLogout', '', { noAuthHandler: true, timeoutMs: 5_000 }),
    // `loginData`, when present, is the second leg of an extended/MFA login: the
    // engine reads it from the X-Mirth-Login-Data header (UserServletInterface
    // .LOGIN_DATA_HEADER) and delegates to its MFA plugin instead of re-checking
    // the password. Matches Swing's client.login-with-header second leg.
    //
    // The login endpoint conveys its result in the BODY (LoginStatus /
    // ExtendedLoginStatus) and returns HTTP 401 for any not-yet-authenticated
    // result — INCLUDING an MFA challenge and plain bad credentials. So we read and
    // return the parsed body for ANY status; the caller inspects `.status` and
    // `.clientPluginClass`. (Using post()/handle() here would throw on the 401 and
    // discard the challenge — the MFA bug.) Only a network failure rejects.
    async login(username, password, loginData) {
        const form = new URLSearchParams({ username, password });
        const h = headers('application/x-www-form-urlencoded');
        if (loginData != null)
            h['X-Mirth-Login-Data'] = String(loginData);
        const res = await engineFetch(BASE + '/users/_login', {
            method: 'POST', headers: h, credentials: 'same-origin', body: form.toString(),
            signal: AbortSignal.timeout(120_000)
        });
        const text = await res.text().catch(() => '');
        assertEngineResponse(res);
        const parsed = parseBody(text);
        // Return the parsed LoginStatus whatever its shape: unwrap() reduces a
        // minimal {status:'SUCCESS'} to the bare string 'SUCCESS', while a full
        // status (or an MFA ExtendedLoginStatus) stays an object. The caller reads
        // both via `result?.status || result` and `result.clientPluginClass`.
        if (parsed !== null && parsed !== undefined && parsed !== '')
            return parsed;
        throw new ApiError(res.status, text || `${res.status} ${res.statusText}`, text);
    },
    logout: () => post('/users/_logout', null, { noAuthHandler: true }),
    current: () => get('/users/current', undefined, { noAuthHandler: true })
};
export const users = {
    list: () => get('/users').then(v => asList(v, 'user')),
    get: (idOrName) => get(`/users/${encodeURIComponent(idOrName)}`),
    create: (user) => post('/users', user, { wrapKey: 'user' }),
    update: (userId, user) => put(`/users/${enc(userId)}`, user, { wrapKey: 'user' }),
    remove: (userId) => del(`/users/${enc(userId)}`),
    updatePassword: (userId, plainPassword) => put(`/users/${enc(userId)}/password`, plainPassword, { contentType: 'text/plain' }),
    checkPassword: (plainPassword) => post('/users/_checkPassword', plainPassword, { contentType: 'text/plain' }),
    isLoggedIn: (userId) => get(`/users/${enc(userId)}/loggedIn`),
    getPreferences: (userId) => get(`/users/${enc(userId)}/preferences`),
    // opts may pass { raw: true } to get the untouched text — needed for values
    // that are themselves XML (e.g. backgroundColor's <awt-color>), which parseBody
    // would otherwise turn into an object.
    getPreference: (userId, name, opts) => get(`/users/${enc(userId)}/preferences/${enc(name)}`, undefined, opts),
    setPreferences: (userId, props) => put(`/users/${enc(userId)}/preferences`, props, { wrapKey: 'properties' }),
    setPreference: (userId, name, value) => put(`/users/${enc(userId)}/preferences/${enc(name)}`, value, { contentType: 'text/plain' }),
    acknowledgeNotification: (userId) => post(`/users/${enc(userId)}/notificationAcknowledged`)
};
/* ===========================================================================
   Channels                                                       /channels
   ========================================================================== */
export const channels = {
    list: (channelIds, pollingOnly) => get('/channels', { channelId: channelIds, pollingOnly }).then(v => asList(v, 'channel')),
    // Transformer templates are base64-wrapped on the wire (engine
    // Base64StringConverter); decode on read and re-encode a clone on write so
    // the in-memory channel keeps plain-text templates. See oie.ts.
    get: (channelId) => get(`/channels/${enc(channelId)}`).then(c => oie.decodeChannelTemplates(c)),
    create: (channel) => post('/channels', oie.encodeChannelTemplates(cloneJson(channel)), { wrapKey: 'channel' }),
    // override=false enables the engine's Swing-parity conflict check: the save is
    // rejected (body "false") when the channel changed after `startEdit` (a Date —
    // when the user opened it for editing). Callers prompt, then retry override=true.
    update: (channelId, channel, override = true, startEdit) => put(`/channels/${enc(channelId)}`, oie.encodeChannelTemplates(cloneJson(channel)), {
        wrapKey: 'channel',
        params: { override, startEdit: startEdit instanceof Date ? fmtStartEdit(startEdit) : startEdit }
    }),
    remove: (channelId) => del(`/channels/${enc(channelId)}`),
    idsAndNames: () => get('/channels/idsAndNames'),
    connectorNames: (channelId) => get(`/channels/${enc(channelId)}/connectorNames`),
    metaDataColumns: (channelId) => get(`/channels/${enc(channelId)}/metaDataColumns`).then(v => asList(v, 'metaDataColumn')),
    portsInUse: () => get('/channels/portsInUse').then(v => asList(v, 'channelPortData')),
    setEnabled: (channelId, enabled) => post(`/channels/${enc(channelId)}/enabled/${enabled}`),
    setInitialState: (channelId, state) => post(`/channels/${enc(channelId)}/initialState/${state}`)
};
export const channelGroups = {
    list: () => get('/channelgroups').then(v => asList(v, 'channelGroup')),
    bulkUpdate: (groups, removedIds = [], override = false) => {
        const form = new FormData();
        form.append('channelGroups', new Blob([stringifyEngineJson({ set: { channelGroup: groups } })], { type: 'application/json' }));
        form.append('removedChannelGroupIds', new Blob([stringifyEngineJson({ set: { string: removedIds } })], { type: 'application/json' }));
        return post('/channelgroups/_bulkUpdate', form, { params: { override } });
    }
};
/* ---- Status & statistics --------------------------------------------------- */
export const status = {
    list: (channelIds, filter, includeUndeployed) => get('/channels/statuses', { channelId: channelIds, filter, includeUndeployed })
        .then(v => asList(v, 'dashboardStatus')),
    initial: (fetchSize = 100, filter) => get('/channels/statuses/initial', { fetchSize, filter }),
    one: (channelId) => get(`/channels/${enc(channelId)}/status`),
    start: (channelId) => post(`/channels/${enc(channelId)}/_start`),
    stop: (channelId) => post(`/channels/${enc(channelId)}/_stop`),
    halt: (channelId) => post(`/channels/${enc(channelId)}/_halt`),
    pause: (channelId) => post(`/channels/${enc(channelId)}/_pause`),
    resume: (channelId) => post(`/channels/${enc(channelId)}/_resume`),
    startConnector: (channelId, metaDataId) => post(`/channels/${enc(channelId)}/connector/${metaDataId}/_start`),
    stopConnector: (channelId, metaDataId) => post(`/channels/${enc(channelId)}/connector/${metaDataId}/_stop`),
    startMany: (channelIds) => postChannelIdForm('/channels/_start', channelIds),
    stopMany: (channelIds) => postChannelIdForm('/channels/_stop', channelIds),
    haltMany: (channelIds) => postChannelIdForm('/channels/_halt', channelIds),
    pauseMany: (channelIds) => postChannelIdForm('/channels/_pause', channelIds),
    resumeMany: (channelIds) => postChannelIdForm('/channels/_resume', channelIds)
};
function postChannelIdForm(path, channelIds) {
    const form = new URLSearchParams();
    for (const id of channelIds)
        form.append('channelId', id);
    return post(path, form.toString(), {
        contentType: 'application/x-www-form-urlencoded',
        params: { returnErrors: true },
        timeoutMs: null
    });
}
export const statistics = {
    list: (channelIds, includeUndeployed) => get('/channels/statistics', { channelId: channelIds, includeUndeployed })
        .then(v => asList(v, 'channelStatistics')),
    one: (channelId) => get(`/channels/${enc(channelId)}/statistics`),
    clear: (channelIdsToConnectors, received = true, filtered = true, sent = true, errored = true) => {
        // Serialize Map<String, List<Integer>> as XStream's native XML — JSON
        // can't unambiguously express a list element of null. A plain
        // {id: null} object 500s, and a NULL list NPEs the donkey layer (it
        // iterates the list). A list of [null] targets metaDataId=null, which
        // the DAO maps to resetChannelStatistics (clears the whole channel) —
        // exactly what the Swing client sends.
        const esc = (s) => String(s).replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
        const entries = Object.entries(channelIdsToConnectors).map(([channelId, metaDataIds]) => {
            const ids = Array.isArray(metaDataIds) && metaDataIds.length ? metaDataIds : [null];
            const items = ids.map(m => (m == null ? '<null/>' : `<int>${m}</int>`)).join('');
            return `<entry><string>${esc(channelId)}</string><list>${items}</list></entry>`;
        });
        return postXml('/channels/_clearStatistics', `<map>${entries.join('')}</map>`, { received, filtered, sent, error: errored });
    },
    clearAll: () => post('/channels/_clearAllStatistics')
};
/* ---- Engine (deploy) --------------------------------------------------------- */
export const engine = {
    deploy: (channelId, returnErrors = true) => post(`/channels/${enc(channelId)}/_deploy`, null, { params: { returnErrors } }),
    // The fan-out deploys run as long as the slowest channel plus the deploy
    // scripts — minutes on a big server — so they carry no client ceiling.
    deployMany: (channelIds, returnErrors = true) => post('/channels/_deploy', { set: { string: channelIds } }, { params: { returnErrors }, timeoutMs: null }),
    undeploy: (channelId, returnErrors = true) => post(`/channels/${enc(channelId)}/_undeploy`, null, { params: { returnErrors } }),
    undeployMany: (channelIds, returnErrors = true) => post('/channels/_undeploy', { set: { string: channelIds } }, { params: { returnErrors } }),
    redeployAll: (returnErrors = true) => post('/channels/_redeployAll', null, { params: { returnErrors }, timeoutMs: null })
};
/* ===========================================================================
   Messages                                       /channels/{id}/messages
   ========================================================================== */
export const messages = {
    search: (channelId, params) => get(`/channels/${enc(channelId)}/messages`, params).then(v => asList(v, 'message')),
    // A COUNT over a large message table is legitimately slow (it's why the
    // browser defers it to an explicit button, like Swing) — no client ceiling.
    count: (channelId, params) => get(`/channels/${enc(channelId)}/messages/count`, params, { timeoutMs: null }),
    get: (channelId, messageId) => get(`/channels/${enc(channelId)}/messages/${enc(messageId)}`),
    maxMessageId: (channelId) => get(`/channels/${enc(channelId)}/messages/maxMessageId`),
    attachments: (channelId, messageId, includeContent = false) => get(`/channels/${enc(channelId)}/messages/${enc(messageId)}/attachments`, { includeContent })
        .then(v => asList(v, 'attachment')),
    attachment: (channelId, messageId, attachmentId) => get(`/channels/${enc(channelId)}/messages/${enc(messageId)}/attachments/${encodeURIComponent(attachmentId)}`),
    // Reattach a DICOM message's pixel-data attachment(s) and return the full,
    // raw Base64 DICOM (Swing getDICOMMessage). Body is the ConnectorMessage.
    getDicom: (channelId, messageId, connectorMessage) => post(`/channels/${enc(channelId)}/messages/${enc(messageId)}/_getDICOMMessage`, connectorMessage, {
        wrapKey: (connectorMessage && connectorMessage['@class']) || 'com.mirth.connect.donkey.model.message.ConnectorMessage',
        raw: true
    }),
    processNew: (channelId, rawData, destinationMetaDataIds, sourceMapEntries) => {
        const sourceMap = new Map();
        for (const entry of sourceMapEntries || []) {
            const separator = entry.indexOf('=');
            if (separator > 0)
                sourceMap.set(entry.slice(0, separator).trim(), entry.slice(separator + 1));
        }
        // Swing's existing RawMessage endpoint distinguishes null (all deployed
        // destinations) from an empty collection (source only). Omit the null
        // field: an empty XML/JSON collection would instead select no destinations.
        return post(`/channels/${enc(channelId)}/messagesWithObj`, {
            rawData, binary: false, overwrite: false, imported: false,
            ...(destinationMetaDataIds === null ? {} : {
                destinationMetaDataIds: { '@class': 'list', int: destinationMetaDataIds || [] }
            }),
            sourceMap: { '@class': 'map', entry: [...sourceMap].map(([key, value]) => ({ string: [key, value] })) }
        }, { wrapKey: 'com.mirth.connect.donkey.model.message.RawMessage' });
    },
    reprocess: (channelId, messageId, replace = false, filterDestinations = false, metaDataIds = []) => post(`/channels/${enc(channelId)}/messages/${enc(messageId)}/_reprocess`, null, {
        params: { replace, filterDestinations, metaDataId: metaDataIds }
    }),
    remove: (channelId, messageId) => del(`/channels/${enc(channelId)}/messages/${enc(messageId)}`),
    // The engine waits for stop/remove/restart to finish before responding, so a
    // large message table can legitimately outlast the normal request ceiling.
    removeAll: (channelId, restartRunningChannels = false, clearStatistics = true) => del(`/channels/${enc(channelId)}/messages/_removeAll`, { restartRunningChannels, clearStatistics }, { timeoutMs: null }),
    auditAccessedPHI: (attributes) => postXml('/channels/_auditAccessedPHIMessage', attributeMapXml(attributes)),
    auditQueriedPHI: (attributes) => postXml('/channels/_auditQueriedPHIMessage', attributeMapXml(attributes)),
    auditExport: (attributes) => postXml('/channels/_auditExportMessages', attributeMapXml(attributes)),
    auditExportSuccess: (attributes) => postXml('/channels/_auditExportMessagesSuccess', attributeMapXml(attributes))
};
function attributeMapXml(attributes) {
    const esc = (value) => String(value).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, '').replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
    return `<map>${Object.entries(attributes)
        .map(([key, value]) => `<entry><string>${esc(key)}</string><string>${esc(value)}</string></entry>`)
        .join('')}</map>`;
}
/* ===========================================================================
   Events                                                          /events
   ========================================================================== */
export const events = {
    search: (params) => get('/events', params).then(v => asList(v, 'serverEvent')),
    count: (params) => get('/events/count', params),
    get: (eventId) => get(`/events/${enc(eventId)}`),
    maxEventId: () => get('/events/maxEventId')
};
/* ===========================================================================
   Alerts                                                          /alerts
   ========================================================================== */
export const alerts = {
    list: () => get('/alerts').then(v => asList(v, 'alertModel')),
    get: (alertId) => get(`/alerts/${enc(alertId)}`),
    statuses: () => get('/alerts/statuses').then(v => asList(v, 'alertStatus')),
    create: (alert) => post('/alerts', alert, { wrapKey: 'alertModel' }),
    update: (alertId, alert) => put(`/alerts/${enc(alertId)}`, alert, { wrapKey: 'alertModel' }),
    remove: (alertId) => del(`/alerts/${enc(alertId)}`),
    enable: (alertId) => post(`/alerts/${enc(alertId)}/_enable`),
    disable: (alertId) => post(`/alerts/${enc(alertId)}/_disable`),
    info: (alertId) => post(`/alerts/${enc(alertId)}/_getInfo`, null),
    options: () => get('/alerts/options')
};
/* ===========================================================================
   Server configuration                                            /server
   ========================================================================== */
export const server = {
    id: () => get('/server/id', null, { raw: true }),
    version: () => get('/server/version', null, { raw: true }),
    buildDate: () => get('/server/buildDate', null, { raw: true }),
    statusCode: () => get('/server/status'),
    time: () => get('/server/time'),
    timezone: () => get('/server/timezone', null, { raw: true }),
    jvm: () => get('/server/jvm', null, { raw: true }),
    about: () => get('/server/about'),
    charsets: () => get('/server/charsets').then(v => asList(v, 'string')),
    settings: () => get('/server/settings'),
    setSettings: (settings) => put('/server/settings', settings, { wrapKey: 'serverSettings' }),
    publicSettings: () => get('/server/publicSettings'),
    updateSettings: () => get('/server/updateSettings'),
    setUpdateSettings: (settings) => put('/server/updateSettings', settings, { wrapKey: 'updateSettings' }),
    configuration: (params) => get('/server/configuration', params),
    // A configuration restore with deploy=true redeploys every channel; cutting
    // it off client-side mid-restore invites a retry the engine is still
    // executing — no client ceiling.
    setConfiguration: (config, deploy = false, overwriteConfigMap = false) => put('/server/configuration', config, { wrapKey: 'serverConfiguration', params: { deploy, overwriteConfigMap }, timeoutMs: null }),
    testEmail: (properties) => post('/server/_testEmail', properties, { wrapKey: 'properties' }),
    generateGUID: () => post('/server/_generateGUID', null, { raw: true }),
    globalScripts: () => get('/server/globalScripts'),
    setGlobalScripts: (scripts) => put('/server/globalScripts', scripts, { wrapKey: 'map' }),
    configurationMap: () => get('/server/configurationMap'),
    setConfigurationMap: (map) => put('/server/configurationMap', map, { wrapKey: 'map' }),
    channelTags: () => get('/server/channelTags').then(v => asList(v, 'channelTag')),
    setChannelTags: (tags) => put('/server/channelTags', { channelTag: tags }, { wrapKey: 'set' }),
    channelDependencies: async () => {
        const dependencies = asList(await get('/server/channelDependencies'), 'channelDependency');
        if (dependencies.some(d => !d || typeof d.dependentId !== 'string' || !d.dependentId || typeof d.dependencyId !== 'string' || !d.dependencyId)) {
            throw new Error('The engine returned invalid channel dependencies. Save was stopped.');
        }
        return dependencies;
    },
    setChannelDependencies: (deps) => put('/server/channelDependencies', { channelDependency: deps }, { wrapKey: 'set' }),
    channelMetadata: () => get('/server/channelMetadata'),
    setChannelMetadata: (metadata) => put('/server/channelMetadata', metadata, { wrapKey: 'map' }),
    resources: () => get('/server/resources'),
    setResources: (resources) => put('/server/resources', resources, { wrapKey: 'list' }),
    reloadResource: (resourceId) => post(`/server/resources/${encodeURIComponent(resourceId)}/_reload`),
    databaseDrivers: () => get('/server/databaseDrivers').then(v => asList(v, 'driverInfo')),
    // List<DriverInfo> serializes as { list: { driverInfo: [...] } } (DriverInfo
    // is @XStreamAlias("driverInfo")). Requires the DATABASE_DRIVERS_EDIT perm.
    setDatabaseDrivers: (drivers) => put('/server/databaseDrivers', { driverInfo: drivers }, { wrapKey: 'list' }),
    passwordRequirements: () => get('/server/passwordRequirements'),
    encryption: () => get('/server/encryption'),
    licenseInfo: () => get('/server/licenseInfo'),
    protocolsAndCipherSuites: () => get('/server/protocolsAndCipherSuites'),
    rhinoLanguageVersion: () => get('/server/rhinoLanguageVersion')
};
/* ===========================================================================
   System info                                                     /system
   ========================================================================== */
export const system = {
    info: () => get('/system/info'),
    stats: () => get('/system/stats')
};
/* ===========================================================================
   Code templates                                /codeTemplateLibraries etc.
   ========================================================================== */
export const codeTemplates = {
    libraries: (includeCodeTemplates = true) => get('/codeTemplateLibraries', { includeCodeTemplates }).then(v => asList(v, 'codeTemplateLibrary')),
    list: () => get('/codeTemplates').then(v => asList(v, 'codeTemplate')),
    get: (id) => get(`/codeTemplates/${enc(id)}`),
    // override=false = engine revision check: rejected (body "false") when the sent
    // revision no longer matches the server's (someone else saved since it was read).
    update: (id, codeTemplate, override = true) => put(`/codeTemplates/${enc(id)}`, codeTemplate, { wrapKey: 'codeTemplate', params: { override } }),
    remove: (id) => del(`/codeTemplates/${enc(id)}`),
    updateLibraries: (libraries, override = true) => put('/codeTemplateLibraries', { codeTemplateLibrary: libraries }, { wrapKey: 'list', params: { override } }),
    bulkUpdate: (libraries, updatedCodeTemplates = [], removedLibraryIds = [], removedCodeTemplateIds = [], override = true) => {
        const form = new FormData();
        const part = (name, value) => form.append(name, new Blob([stringifyEngineJson(value)], { type: 'application/json' }));
        part('libraries', { list: { codeTemplateLibrary: libraries } });
        part('updatedCodeTemplates', { list: { codeTemplate: updatedCodeTemplates } });
        part('removedLibraryIds', { set: { string: removedLibraryIds } });
        part('removedCodeTemplateIds', { set: { string: removedCodeTemplateIds } });
        return post('/codeTemplateLibraries/_bulkUpdate', form, { params: { override } });
    }
};
/* ===========================================================================
   Extensions                                                  /extensions
   ========================================================================== */
export const extensions = {
    connectors: () => get('/extensions/connectors'),
    plugins: () => get('/extensions/plugins'),
    metadata: (name) => get(`/extensions/${encodeURIComponent(name)}`),
    isEnabled: (name) => get(`/extensions/${encodeURIComponent(name)}/enabled`),
    setEnabled: (name, enabled) => post(`/extensions/${encodeURIComponent(name)}/_setEnabled`, null, { params: { enabled } }),
    properties: (name) => get(`/extensions/${encodeURIComponent(name)}/properties`),
    setProperties: (name, properties) => put(`/extensions/${encodeURIComponent(name)}/properties`, properties, { wrapKey: 'properties' })
};
/* ===========================================================================
   Database tasks                                            /databaseTasks
   ========================================================================== */
export const databaseTasks = {
    list: () => get('/databaseTasks'),
    get: (taskId) => get(`/databaseTasks/${encodeURIComponent(taskId)}`),
    run: (taskId) => post(`/databaseTasks/${encodeURIComponent(taskId)}/_run`),
    cancel: (taskId) => post(`/databaseTasks/${encodeURIComponent(taskId)}/_cancel`)
};
const api = {
    get, post, put, del, getXml, postXml, putXml, asList, parseBody, onSessionExpired, onEngineUnknown,
    auth, users, channels, channelGroups, status, statistics, engine,
    messages, events, alerts, server, system, codeTemplates, extensions, databaseTasks
};
export default api;
