/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
const widthError = 'Enter comma-separated whole numbers from 1 to 2147483647, or leave blank.';
const nameError = 'Enter comma-separated XML column names starting with a letter, underscore or colon.';
// XML 1.0 NameStartChar/NameChar (also used by the engine's DatabaseReceiver).
// The Delimited property setter also accepts Java Character.isLetter names
// outside this range, including ª, µ and º. Keep both accepted wire shapes.
const isEngineLiteral = (entry) => entry === null || typeof entry === 'boolean';
const engineString = (entry) => isEngineLiteral(entry) ? String(entry) : entry;
const XML_NAME = /^[:A-Z_a-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD\u{10000}-\u{EFFFF}][:A-Z_a-z\u00C0-\u00D6\u00D8-\u00F6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD\u{10000}-\u{EFFFF}\-.0-9\u00B7\u0300-\u036F\u203F-\u2040]*$/u;
const ENGINE_NAME = /^[:_\p{L}][:_\p{L}\p{Nd}.\-]*$/u;
export function dataTypeListText(value, item) {
    if (value == null)
        return '';
    if (typeof value !== 'object')
        return String(value);
    if (!Array.isArray(value) && Object.keys(value).some(key => key !== item && !key.startsWith('@')))
        return JSON.stringify(value);
    const entries = Array.isArray(value) ? value : value[item];
    if (entries === null && item === 'string')
        return 'null';
    if (entries == null)
        return '';
    return (Array.isArray(entries) ? entries : [entries]).map(entry => typeof entry === 'object' ? JSON.stringify(entry) : String(entry)).join(',');
}
/** Accept existing singleton/array wire shapes and legacy editor text. Keep
 * valid wire objects intact, including attributes. Unknown children are errors,
 * never silently dropped. Empty lists become an omitted property. */
export function normalizeDataTypeList(value, item, xmlNames = false) {
    if (value == null || (typeof value === 'string' && !value.trim()))
        return {};
    let values;
    let wire;
    if (typeof value === 'object' && !Array.isArray(value)) {
        if (Object.keys(value).some(key => key !== item && !key.startsWith('@'))) {
            return { error: `Unrecognized ${item} array contents. Correct the list before saving.` };
        }
        wire = value;
        let entries = value[item];
        if (item === 'string' && (Array.isArray(entries) ? entries.some(isEngineLiteral) : isEngineLiteral(entries))) {
            entries = Array.isArray(entries) ? entries.map(engineString) : engineString(entries);
            wire = { ...value, string: entries };
        }
        values = entries == null ? [] : Array.isArray(entries) ? entries : [entries];
    }
    else if (Array.isArray(value)) {
        values = value;
    }
    else if (typeof value === 'string' || typeof value === 'number') {
        values = String(value).split(',').map(part => part.trim());
        // Java String.split drops trailing empty fields, but keeps interior ones.
        while (values.length > 1 && values[values.length - 1] === '')
            values.pop();
    }
    else {
        return { error: item === 'int' ? widthError : nameError };
    }
    if (!values.length) {
        // An XStream reference or future metadata-only wrapper is not evidence
        // of an empty array. Preserve it and ask for correction rather than
        // silently deleting possibly meaningful data during a channel save.
        if (wire && Object.keys(wire).some(key => key !== item && key !== '@class' && key !== '@version')) {
            return { error: `Unrecognized ${item} array contents. Correct the list before saving.` };
        }
        return {};
    }
    if (item === 'int') {
        if (!values.every(part => (typeof part === 'string' || typeof part === 'number')
            && /^\+?\d+$/.test(String(part)) && Number.isInteger(Number(part))
            && Number(part) > 0 && Number(part) <= 2147483647))
            return { error: widthError };
        return { value: wire || { int: values.map(Number) } };
    }
    if (!values.every(part => typeof part === 'string' && part.length > 0
        && (!xmlNames || XML_NAME.test(part) || ENGINE_NAME.test(part)))) {
        return { error: nameError };
    }
    return { value: wire || { string: values } };
}
/** Normalize only the three Delimited array properties; all unknown groups,
 * sibling fields, class/version attributes and nonempty wire arrays survive. */
export function normalizeDelimitedProperties(props) {
    const errors = [];
    if (!props || typeof props !== 'object')
        return errors;
    for (const [groupKey, fieldKey, item] of [
        ['serializationProperties', 'columnWidths', 'int'],
        ['serializationProperties', 'columnNames', 'string'],
        ['deserializationProperties', 'columnWidths', 'int'],
    ]) {
        const group = props[groupKey];
        if (!group || typeof group !== 'object' || !(fieldKey in group))
            continue;
        const result = normalizeDataTypeList(group[fieldKey], item, item === 'string');
        if (result.error)
            errors.push(`${groupKey}.${fieldKey}: ${result.error}`);
        else if (result.value === undefined)
            delete group[fieldKey];
        else
            group[fieldKey] = result.value;
    }
    return errors;
}
/** Final save guard covers unvisited connector and response panels, including
 * legacy web channels whose null/empty widths otherwise keep losing columns. */
export function normalizeChannelDataTypeArrays(channel) {
    const destinations = channel.destinationConnectors?.connector;
    const connectors = [channel.sourceConnector, ...(Array.isArray(destinations) ? destinations : destinations ? [destinations] : [])];
    const errors = [];
    for (const connector of connectors) {
        for (const key of ['transformer', 'responseTransformer']) {
            const transformer = connector?.[key];
            for (const side of ['inbound', 'outbound']) {
                if (transformer?.[`${side}DataType`] !== 'DELIMITED')
                    continue;
                for (const error of normalizeDelimitedProperties(transformer[`${side}Properties`])) {
                    errors.push(`${connector.name || 'Source'} ${key} ${side}: ${error}`);
                }
            }
        }
    }
    if (errors.length)
        throw new Error(`Invalid Delimited Text properties:\n${errors.join('\n')}`);
}
