/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/*
 * Import version guard — a faithful port of Swing's Frame.promptObjectMigration
 * (client/src/.../Frame.java) via MigrationUtil. Three branches on the export's
 * version vs the connected server's version:
 *
 *   same    -> import silently
 *   newer   -> BLOCK (alertInformation, title "Information")
 *   older / unknown -> CONFIRM the automatic conversion (title "Select an Option")
 *
 * Parity details that matter:
 *   - Version source is the ROOT element's `version` attribute
 *     (MigrationUtil.getSerializedObjectVersion / XStream VERSION_ATTRIBUTE_NAME).
 *   - Compare normalizes BOTH versions to exactly 3 components
 *     (MigrationUtil.compareVersions(v1, v2, 3)) — so 4.6.0.x == 4.6.0.
 *   - Message strings are verbatim from Frame.promptObjectMigration with the
 *     product name "Open Integration Engine" (BrandingConstants.PRODUCT_NAME).
 *
 * Swing guards channels, channel groups, and server configuration with this.
 * Alert imports also use it because issue #40 explicitly requires the same
 * forward-version protection alongside alert collision handling.
 */
import * as store from './store.js';
const PRODUCT = 'Open Integration Engine';
// MigrationUtil.compareVersions(v1, v2, 3): pad/truncate both to 3 components.
function compareVersions(v1, v2) {
    const norm = (v) => {
        const parts = String(v).split('.');
        while (parts.length < 3)
            parts.push('0');
        return parts.slice(0, 3).map((n) => parseInt(n, 10) || 0);
    };
    const a = norm(v1);
    const b = norm(v2);
    for (let i = 0; i < 3; i++) {
        if (a[i] < b[i])
            return -1;
        if (a[i] > b[i])
            return 1;
    }
    return 0;
}
/**
 * Verdict for importing an export stamped `exportVersion` (Swing objectName, e.g.
 * "channel", "channel or group", "server configuration"):
 *   { action: 'ok' }
 *   { action: 'block',   message }   — newer than the server
 *   { action: 'confirm', message }   — older/unknown; ask before converting
 */
// Call sites pass the Swing export identifiers; map them to display names so the
// localized messages never render an English noun mid-sentence. Unknown/Chinese
// names pass through unchanged.
const OBJECT_DISPLAY_NAMES = {
    'channel': '通道',
    'channel or group': '通道或组',
    'group': '组',
    'alert': '警报',
    'server configuration': '服务器配置',
    'configuration map': '配置映射',
    'code template': '代码模板',
};
export function checkImportVersion(exportVersion, objectName = '文件') {
    objectName = OBJECT_DISPLAY_NAMES[objectName] ?? objectName;
    const server = store.getState('serverVersion');
    if (!server)
        return { action: 'ok' }; // server version unknown: engine stays the authority
    if (exportVersion) {
        const comparison = compareVersions(exportVersion, server);
        if (comparison === 0)
            return { action: 'ok' };
        if (comparison > 0) {
            return {
                action: 'block',
                message: `正在导入的${objectName}来自 ${PRODUCT} ${exportVersion} 版本。\n`
                    + `您当前使用的版本为 ${PRODUCT} ${server}。\n`
                    + `无法导入该${objectName}，因为它来自更高版本的 ${PRODUCT}。`
            };
        }
        // older
        return {
            action: 'confirm',
            message: `正在导入的${objectName}来自 ${PRODUCT} ${exportVersion} 版本。\n`
                + `您当前使用的版本为 ${PRODUCT} ${server}。\n`
                + `是否将该${objectName}自动转换为 ${server} 格式？`
        };
    }
    // unknown version
    return {
        action: 'confirm',
        message: `正在导入的${objectName}来自较旧或未知版本的 ${PRODUCT}。\n`
            + `您当前使用的版本为 ${PRODUCT} ${server}。\n`
            + `是否将该${objectName}自动转换为 ${server} 格式？`
    };
}
/** Verdict from parsed export XML: the ROOT element's version attribute, Swing-style. */
export function checkImportVersionFromDoc(doc, objectName) {
    const version = doc?.documentElement?.getAttribute('version');
    return checkImportVersion(version, objectName);
}
