/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/*
 * Shared variable-reference lists shown beside code editors: the classic
 * Administrator's "Destination Mappings" velocity tokens (connector templates)
 * and the Rhino scope cheat-sheet for channel scripts (filter/transformer steps,
 * auth scripts). Each entry is [label, insertText].
 */
export const DESTINATION_MAPPINGS = [
    ['通道 ID', '${channelId}'],
    ['通道名称', '${channelName}'],
    ['消息 ID', '${message.messageId}'],
    ['原始数据', '${message.rawData}'],
    ['转换后数据', '${message.transformedData}'],
    ['编码后数据', '${message.encodedData}'],
    ['消息来源', '${message.source}'],
    ['消息类型', '${message.type}'],
    ['消息版本', '${message.version}'],
    ['日期', '${date}'],
    ['格式化日期', "${date.get('yyyy-M-d H.m.s')}"],
    ['时间戳', '${SYSTIME}'],
    ['唯一 ID', '${UUID}'],
    ['原始文件名', '${originalFilename}'],
    ['计数', '${COUNT}'],
    ['XML 实体编码器', '${XmlUtil.encode()}'],
    ['XML 美化打印', '${XmlUtil.prettyPrint()}'],
    ['转义 JSON 字符串', '${JsonUtil.escape()}'],
    ['JSON 美化打印', '${JsonUtil.prettyPrint()}'],
    ['CDATA 标签', '<![CDATA[]]>'],
    ['DICOM 消息原始数据', '${DICOMMESSAGE}']
];
/* Rhino script scope — the identifiers available inside filter/transformer steps
   and channel scripts (JavaScript context). */
export const SCRIPT_REFERENCE = [
    ['入站消息', 'msg'],
    ['转换后消息', 'tmp'],
    ['连接器消息', 'connectorMessage'],
    ['通道 ID', 'channelId'],
    ['通道名称', 'channelName'],
    ['通道映射', "$c('key')"],
    ['通道映射（写入）', "$c('key', value)"],
    ['源映射', "$s('key')"],
    ['全局映射', "$g('key')"],
    ['全局通道映射', "$gc('key')"],
    ['响应映射', "$r('key')"],
    ['配置映射', "$cfg('key')"],
    ['附件', 'getAttachments()'],
    ['日志记录器', "logger.info('')"],
    ['唯一 ID', 'UUIDGenerator.getUUID()'],
    ['日期工具', "DateUtil.getCurrentDate('yyyyMMddHHmmss')"]
];
