/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
export function passwordRequirementHints(req) {
    const r = (req && (req.passwordRequirements || req)) || {};
    const num = (k) => { const v = Number(r[k]); return Number.isFinite(v) ? v : 0; };
    const hints = [];
    const minLength = num('minLength');
    if (minLength > 0)
        hints.push(`至少 ${minLength} 个字符`);
    const rule = (key, noun) => {
        const v = num(key);
        if (v === -1)
            hints.push(`不含${noun}`);
        else if (v === 1)
            hints.push(`1 个${noun}`);
        else if (v > 1)
            hints.push(`${v} 个${noun}`);
    };
    rule('minUpper', '大写字母');
    rule('minLower', '小写字母');
    rule('minNumeric', '数字');
    rule('minSpecial', '特殊字符');
    return hints;
}
