/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */
/*
 * Browser-side user preferences (the web-admin equivalent of the Swing
 * Administrator settings panel). These are per-browser, stored in localStorage —
 * only the settings that actually map to web-admin behavior are kept; the
 * Swing panel's RSyntaxTextArea/editor shortcut settings do not apply (Monaco
 * manages its own). Namespaced per engine AND per user (scopedKey) so a different
 * engine, or a different user on the same browser, keeps separate settings.
 */
import { scopedKey } from './store.js';
const BASE_KEY = 'webadmin-prefs';
const storageKey = () => scopedKey(BASE_KEY);
/*
 * The dashboard's poll interval, in seconds — Swing's default, and deliberately
 * the same number.
 *
 * The status poll fetches EVERY deployed channel's statuses on every tick, so its
 * cost is the channel count times the rate. At five seconds a thousand-channel
 * engine was being asked for the whole board twelve times a minute, per open
 * dashboard; the Swing client has always asked three times a minute
 * (StatusUpdater's DEFAULT_INTERVAL_TIME), and its own tooltip tells operators to
 * raise it further for "slower servers with more channels".
 *
 * Anyone who wants the faster board still has the preference on Settings →
 * Administrator, which is exactly how the desktop client offers it.
 */
export const DASHBOARD_REFRESH_SECONDS = 20;
export const PREF_DEFAULTS = {
    dashboardRefreshSeconds: DASHBOARD_REFRESH_SECONDS,
    messagePageSize: 20,
    eventPageSize: 20,
    formatMessages: true,
    confirmReprocessRemove: true,
    importLibrariesWithChannels: 'ask',
    exportLibrariesWithChannels: 'ask',
    newChannelDefault: 'ask',
    newAlertDefault: 'ask',
    showViewSwitch: true,
    dashboardView: 'classic',
    cardsGroupBy: 'none',
    cardsLifetime: false,
    tableDensity: 'normal',
    fontUi: 'inter',
    fontMono: 'jetbrains',
    paletteRecent: [],
    navLayout: null
};
const listeners = new Set();
/** Observe same-window preference edits, including resets. */
export function onPrefsChange(listener) {
    listeners.add(listener);
    return () => { listeners.delete(listener); };
}
let cache = null;
let cacheKey = null; // storageKey the cache belongs to; re-reads when the server namespace changes
function all() {
    const key = storageKey();
    if (cache && cacheKey === key)
        return cache;
    let next;
    try {
        next = { ...PREF_DEFAULTS, ...JSON.parse(localStorage.getItem(key) || '{}') };
    }
    catch {
        next = { ...PREF_DEFAULTS };
    }
    cache = next;
    cacheKey = key;
    return next;
}
/** Read one preference (falls back to its default). */
export function getPref(key) {
    const v = all()[key];
    return v === undefined ? PREF_DEFAULTS[key] : v;
}
/** Merge and persist a set of preferences. */
export function setPrefs(obj) {
    cache = { ...all(), ...obj };
    cacheKey = storageKey();
    try {
        localStorage.setItem(storageKey(), JSON.stringify(cache));
    }
    catch { /* private mode */ }
    for (const listener of listeners)
        listener();
}
/** Reset all preferences to their defaults. */
export function resetPrefs() {
    cache = { ...PREF_DEFAULTS };
    cacheKey = storageKey();
    try {
        localStorage.removeItem(storageKey());
    }
    catch { /* private mode */ }
    for (const listener of listeners)
        listener();
}
