/*
 * Builds the Node server: server/*.ts -> the CommonJS server/*.js twins that
 * `node server/index.js` actually runs (tsconfig.server.json; comments are
 * preserved by tsc). Both the .ts source and the generated .js are checked in —
 * edit the .ts, then rerun this (or `npm run build`; `npm run dev`/`npm start`
 * also regenerate on boot). Mirrors tools/build-core.mjs for client/core.
 */
import { spawnSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const serverDir = path.join(root, 'server');

const sources = readdirSync(serverDir).filter(n => n.endsWith('.ts') && !n.endsWith('.d.ts'));
if (!sources.length) { console.log('[build-server] no TypeScript server modules'); process.exit(0); }

// typescript is a devDependency; on a production install (`npm ci --omit=dev`)
// it is absent — the committed generated twins are current, so skip gracefully
// instead of crashing `npm start`.
const tsc = path.join(root, '..', 'node_modules', 'typescript', 'bin', 'tsc');
if (!existsSync(tsc)) {
    console.log('[build-server] typescript not installed (production install?) — using the committed generated files.');
    process.exit(0);
}
const res = spawnSync(process.execPath, [tsc, '-p', path.join(root, 'tsconfig.server.json')], { stdio: 'inherit' });
if (res.status !== 0) process.exit(res.status ?? 1);

// tsc has no banner option — stamp the generated files so nobody edits them.
// The stamp goes AFTER a shebang line (index.js) so the executable bit works.
const BANNER = '/* GENERATED by tools/build-server.mjs from the sibling .ts source — edit the .ts, not this file. */\n';
for (const src of sources) {
    const out = path.join(serverDir, src.slice(0, -3) + '.js');
    let text = readFileSync(out, 'utf8');
    if (text.includes(BANNER)) continue;
    if (text.startsWith('#!')) {
        const nl = text.indexOf('\n') + 1;
        text = text.slice(0, nl) + BANNER + text.slice(nl);
    } else {
        text = BANNER + text;
    }
    writeFileSync(out, text);
}
console.log(`[build-server] built ${sources.length} server module(s): ${sources.map(n => n.slice(0, -3)).join(', ')}`);
