/*
 * Builds the TypeScript core modules: client/core/*.ts -> *.js, the raw-served
 * framework files the app bundle and runtime plugins import by stable URL
 * (/core/api.js, /core/pkg-api.js, ...). Emits with tsc (tsconfig.emit.json)
 * rather than esbuild so COMMENTS SURVIVE into the served .js — plugin authors
 * read these files in the browser. Transpile-only semantics still hold: every
 * import specifier is kept as-is and resolves at runtime through the page
 * importmap / served paths — one shared framework instance. Type-only imports
 * (`import type`, enforced by verbatimModuleSyntax) are erased, so pure type
 * modules (wire-types, oie-schema.d.ts) never become runtime requests.
 *
 * Both the .ts source and the generated .js are checked in (same model as the
 * connector .jsx -> .js pairs): edit the .ts, then rerun this (or `npm run
 * build`; `npm run dev`/`npm start` also regenerate on boot). A core module
 * with no .ts source is plain JavaScript and is left as-is.
 */
import { spawnSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dirs = [path.join(root, 'client', 'core'), path.join(root, 'client', 'connectors')];

const sources = dirs.flatMap((dir) => readdirSync(dir)
    .filter(n => (n.endsWith('.ts') || n.endsWith('.tsx')) && !n.endsWith('.d.ts'))
    .map(n => path.join(dir, n)));
if (!sources.length) { console.log('[build-core] no TypeScript client modules'); process.exit(0); }

// The workspace-hoisted tsc shim (TS 7 does not export a require()-able bin path).
// typescript is a devDependency; on a production install (`npm ci --omit=dev`)
// it is absent — the committed generated twins are current, so skip gracefully
// instead of crashing `npm start`.
const tsc = path.join(root, '..', 'node_modules', 'typescript', 'bin', 'tsc');
if (!existsSync(tsc)) {
    console.log('[build-core] typescript not installed (production install?) — using the committed generated files.');
    process.exit(0);
}
const res = spawnSync(process.execPath, [tsc, '-p', path.join(root, 'tsconfig.emit.json')], { stdio: 'inherit' });
if (res.status !== 0) process.exit(res.status ?? 1);

// tsc has no banner option — stamp the generated files so nobody edits them.
const BANNER = '/* GENERATED by tools/build-core.mjs from the sibling TypeScript source — edit the .ts/.tsx, not this file. */\n';
for (const src of sources) {
    const out = src.replace(/\.tsx?$/, '.js');
    const text = readFileSync(out, 'utf8');
    if (!text.startsWith(BANNER)) writeFileSync(out, BANNER + text);
}
console.log(`[build-core] built ${sources.length} client module(s): ${sources.map(n => path.basename(n).replace(/\.tsx?$/, '')).join(', ')}`);
